### ISSUE TITLE
mlocate -- 

### ISSUE THREAD

**Issue by remo7777** [sdrausty/termux-archlinux#1]
```updatedb``` not working

**Comment by sdrausty** [comment]
Can you provide a little more information. A screenshot and output from `setupTermuxArch.sh sysinfo` should help in clarifying and possibly resolving your issue.

**Comment by sdrausty** [comment]
Here's a little information on mlocate. Hopefully this will be helpful https://superuser.com/questions/341232/faster-alternatives-to-find-and-locate#341289

**Comment by sdrausty** [comment]
That document brings us our first alternative `pacman -S the_silver_searcher`.  What do you think of `ag` @remo7777?

**Comment by sdrausty** [comment]
`mlocate` appears to be working fine:
```
[04:48 mlocate ]$ l
total 3572568
drwxr-x---  2 root       4096 Nov 28 03:40 .
drwxr-xr-x 16 root       4096 Nov 28 03:39 ..
-rw-------  1 root 3658297344 Nov 28 04:48 mlocate.db.REZPNb
[04:48 mlocate ]$ l
total 3576128
drwxr-x---  2 root       4096 Nov 28 03:40 .
drwxr-xr-x 16 root       4096 Nov 28 03:39 ..
-rw-------  1 root 3661942784 Nov 28 04:48 mlocate.db.REZPNb
```
How much time did you give `updatedb` to do it's job?  Did you let it finish is' work?

**Comment by remo7777** [comment]
bash setupTermuxArch.sh sysinfo
``` 
[1;32mBegin setupTermuxArch debug information.

Tue Nov 28 15:33:02 IST 2017

cat /proc/cpuinfo results:

Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 5
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 6
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 7
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: Qualcomm Technologies, Inc MSM8937

dpkg --print-architecture result:

aarch64

getprop ro.product.cpu.abi result:

arm64-v8a

getprop ro.product.device result:

K53a48

Download directory information results.

lrwxrwxrwx 1 u0_a126 u0_a126 28 Nov 17 07:33 /data/data/com.termux/files/home/storage/downloads -> /storage/emulated/0/Download
ls: cannot access '/data/data/com.termux/files/home/downloads': No such file or directory
/sdcard/Download exists
/storage/emulated/0/Download exists

uname -mo results:

aarch64 Android

End setupTermuxArch debug information.

Post this information along with information regarding your issue at https://github.com/sdrausty/TermuxArch/issues.  This debugging information is found in /data/data/com.termux/files/home/setupTermuxArchDebug.log.  If you think screenshots will help in resolving this matter better, include them in your post please.  Submit this information if you plan to open up an issue at https://github.com/sdrausty/TermuxArch/issues to improve this installation script along with a screenshot of your topic.  

[0mThank you for using [1;32m`setupTermuxArch.sh`[0m 🏁   ```

**Comment by remo7777** [comment]
ok its worked on your device then i ll try on my device..👍

**Comment by remo7777** [comment]
![screenshot_20171128-154902](https://user-images.githubusercontent.com/28594846/33314577-172751b8-d454-11e7-8269-53a2db350ef7.jpeg)

**Comment by sdrausty** [comment]
Thanks for posting the additional information requested. You might want to try:

Speeding up locate

Ensure it is indexing the locations you are interested in. Read the man page and make use of whatever options are appropriate to your task.
```
   -U <dir>
          Create slocate database starting at path <dir>.

   -d <path>
          --database=<path> Specifies the path of databases to search  in.


   -l <level>
          Security  level.   0  turns  security checks off. This will make
          searchs faster.   1  turns  security  checks  on.  This  is  the
          default
```
From the superuser link.  Also, if you want to see what`updatedb` is doing, then:

```
[05:45 home ]$ cd /var/lib/mlocate/
[05:46 mlocate ]$ ls -al
```

![screenshot_20171128-054921](https://user-images.githubusercontent.com/27742457/33315869-edf61e04-d3ff-11e7-9009-21759ee0857d.png)

**Comment by remo7777** [comment]
![screenshot_20171128-162948](https://user-images.githubusercontent.com/28594846/33316285-720a3550-d459-11e7-9bca-39c2df3c900d.jpeg)
oh.. its progressing ... thank..you..
after complete i ll close this issue..

**Comment by sdrausty** [comment]
@remo7777 it appears that you have found a bug. Congratulations.  Thank you. 
```
[06:34 home ]$ cd /var/lib/mlocate/;l
total 9338416
drwxr-x---  2 root       4096 Nov 28 08:40 .
drwxr-xr-x 16 root       4096 Nov 28 08:39 ..
-rw-------  1 root 9562292224 Nov 28 11:35 mlocate.db.REZPNb
```
`updatedb` makes an excessively large database file.  The reason it stopped is not because it completed correctly, but by consuming all the userspace on device.  Remove the database file.  Then try using one of the options like -U.   The course of action is probably to contact Arch developers.  Possibly a future update through `pacman -Syu` will resolve this matter too. 

I used to use locate regularly when I was new to Linux. It was very helpful. I usually don't use locate anymore. I have no need to use it.  When I want to find something, I usually use find.  Other similar helpful programs are `ack-grep` in Termux, which is `ack` in Arch. These two search for matching strings in files, and output matching strings with found files.  Master `find`.  It is a very strong tool.  Install `findutils` in either Arch or Termux. This is the full version of `find`.

**Comment by remo7777** [comment]
😝😝
3.7GB ha..ha..

**Comment by remo7777** [comment]
i m also new on linux
ok i ll follow ur steps...

**Comment by remo7777** [comment]
sorry for disturbing u
one question how to use ```termux-tts-speak``` with examples plz
free tym reply me plz....
# thank you

**Comment by sdrausty** [comment]
@remo7777 ask your question on Gitter or at https://plus.google.com/u/0/communities/101692629528551299417. I used that a long time ago and from what I remember, try `pkg up espeak`.  You might enjoy this as much as I do.
