### ISSUE TITLE
Permission Denied when creating symlink to ca-certificate

### ISSUE THREAD

**Issue by texasbruce** [sdrausty/termux-archlinux#11]
I did not seem to find a same issue so I opened it. The installation failed with error:

Uncompressing ArchLinuxARM-aarch64-latest.tar.gz will take a long time; Be patient:
tar: can't create symlink './etc/ca-certificates/extracted/cadir/d7746a63.0' to 'D-TRUST_Root_Class_3_CA_2_EV_2009.pem': Permission denied

TermuxArch warning.  Signal generated!

setupTermuxArch.sh  v1.6: DONE 🏁

After this, no startarch binary created.

I am using Huawei P20Pro EMUI 8. 

I tried with bloom. Same issue.

proot test returns nothing.

ls arch/etc/ca-certificates/extracted/cadir/ returns nothing.

**Comment by sdrausty** [comment]
@texasbruce try `setupTermuxArch.sh refresh `.  Should this not help, share information about your experience with `setupTermuxArch.sh sysinfo`.

**Comment by texasbruce** [comment]
refresh failed:

The root directory structure is incorrect; Cannot continue setupTermuxArch.sh refresh.

setupTermuxArch.sh refresh v1.6: DONE 🏁

sysinfo return is attached.
[sysinfo.txt](https://github.com/sdrausty/termux-archlinux/files/2276610/sysinfo.txt)

**Comment by sdrausty** [comment]
```
`termux-info` results:

Updatable packages:
gpgv/stable 2.2.9-2 aarch64 [upgradable from: 2.2.9-1]
openssh/stable 7.7p1-4 aarch64 [upgradable from: 7.7p1-3]
proot/stable 5.1.107-15 aarch64 [upgradable from: 5.1.107-11]
```

Update your Termux installation, especially prior.  

```
Android version:
8.1.0
```

If reinstalling after updating Termux does not work, join the discussion at https://github.com/termux/proot/issues?q=is%3Aissue+Android+8 since that may be the best way to resolve this issue.

**Comment by sdrausty** [comment]
```
`termux-info` results:

Updatable packages:
gpgv/stable 2.2.9-2 aarch64 [upgradable from: 2.2.9-1]
openssh/stable 7.7p1-4 aarch64 [upgradable from: 7.7p1-3]
proot/stable 5.1.107-15 aarch64 [upgradable from: 5.1.107-11]
```

Update your Termux installation, especially prior.  

```
Android version:
8.1.0
```

If reinstalling after updating Termux does not work, join the discussion at https://github.com/termux/proot/issues?q=is%3Aissue+Android+8 since that may be the best way to resolve this issue.

**Comment by sdrausty** [comment]
The most recent version takes this error into account.  Use `setupTermuxArch.sh refresh` to update your Arch Linux in Termux PRoot.  Should refresh not accomplish its' task, reinstall.

**Comment by michaelgold** [comment]
I am still getting this error. Were the issues mentioned in [this thread](https://github.com/termux/termux-packages/issues/2735) already resolved?

**Comment by sdrausty** [comment]
> Were the issues mentioned in [this thread](https://github.com/termux/termux-packages/issues/2735) already resolved?

@michaelgold unknown; spinner is currently dropped.  Spinner was triggering the error.
