### ISSUE TITLE
" TermuxArch warning: Script signal 1 generated! "

### ISSUE THREAD

**Issue by nxd84** [sdrausty/termux-archlinux#12]
Hello sir,
I am user of aarch64, android 7.1.2 .
When I going to install ArchLinux on termux, at the stage of "🕚 Uncompressing ArchLinuxARM-aarch64-latest.tar.gz" an error comes displaying this massage " TermuxArch warning: Script signal 1 generated! "
" SetupTermuxArch.sh v1.6: DONE "
Please solve this issue.
Note that, I used ArchLinux in the same  device 5 days ago. But today after uninstalling termux when I reinstalled it (termux) and going to install ArchLinux on it (termux) the error came. Now I request, please fix this problem as soon as possible.
Thanks in advance.

**Comment by sdrausty** [comment]
The most recent version takes this error into account.  Use `setupTermuxArch.sh refresh` to update your Arch Linux in Termux PRoot.  Should refresh not accomplish its' task, reinstall.

**Comment by nxd84** [comment]
Thanks ifs working

**Comment by sdrausty** [comment]
You're welcome.

**Comment by sdrausty** [comment]
Thanks for confirmed.
