### ISSUE TITLE
i get dns errors with a fresh install when previous versions worked

### ISSUE THREAD

**Issue by tsrnc2** [sdrausty/termux-archlinux#13]
On a fresh install dns fails to work. All network functions fail as a result. /etc/resolv.conf  appears to be empty. Direct ip access still works. Dns outside the proot inside termux works fine. Previous installations did not have thus problem.

**Comment by sdrausty** [comment]
@tsrnc2 I cannot reproduce the error you mentioned:
```
[11:51 etc ]$ cat resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
```

Try `setupTermuxArch.sh refresh`.  This should populate resolve.conf with the necessary configuration.
