### ISSUE TITLE
Postgresql shmget error 

### ISSUE THREAD

**Issue by yeasin6152** [SDRausty/termux-archlinux#14]
[root12:28test]$su
[root@localhost test]# su -l postgres
[postgres@localhost ~]$ initdb -D '/var/lib/postgres/data'
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgres/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting dynamic shared memory implementation ... sysv
creating configuration files ... ok
running bootstrap script ... 2018-09-11 06:31:46.177 UTC [31503] FATAL:  could not create shared memory segment: Function not implemented
2018-09-11 06:31:46.177 UTC [31503] DETAIL:  Failed system call was shmget(key=1, size=56, 03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgres/data"
[postgres@localhost ~]$

**Comment by abicorios** [comment]
+1
I was trying to initialize the postgresql. And I had this error too.

**Comment by yeasin6152** [comment]
Please solve me, when i create first postgresql database. It show error...

sudo -u postgres initdb --locale en_US.UTF-8 -E UTF8 -D '/var/lib/postgres/data'
![Screenshot_20190318-232531](https://user-images.githubusercontent.com/37853204/54549874-2fc7dd80-49d5-11e9-9fc6-a19f04cbce36.png)

**Comment by yeasin6152** [comment]
Please solve that, postgresql not config first time.
![Screenshot_20190318-232758](https://user-images.githubusercontent.com/37853204/54550127-a06efa00-49d5-11e9-8ff0-ed49f7a2964c.png)

**Comment by T4P4N** [comment]
@SDRausty is there any workaround for this issue or i have to use native termux  for postgresql?

**Comment by T4P4N** [comment]
termux already have libandroid-shmem
So all you need is to run:
`pkg i postgresql`
`
┌[rolex@localhost] [/dev/pts/1]
└[~]> initdb $PREFIX/var/lib/postgresql
The files belonging to this database system will be owned by user "u0_a101".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /data/data/com.termux/files/usr/var/lib/postgresql ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... sysv
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Asia/Kolkata
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql -l logfile start

┌[rolex@localhost] [/dev/pts/1]
└[~]>
┌[rolex@localhost] [/dev/pts/1] [1]
└[~]> pg_ctl -D /data/data/com.termux/files/usr/var/lib/postgresql start
waiting for server to start....2020-01-15 14:30:35.504 IST [10854] LOG:  starting PostgreSQL 12.1 on aarch64-unknown-linux-android, compiled by Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn), 64-bit
2020-01-15 14:30:35.506 IST [10854] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2020-01-15 14:30:35.506 IST [10854] LOG:  listening on IPv6 address "::1", port 5432
2020-01-15 14:30:35.515 IST [10854] LOG:  listening on Unix socket "/data/data/com.termux/files/usr/tmp/.s.PGSQL.5432"
2020-01-15 14:30:35.571 IST [10858] LOG:  database system was shut down at 2020-01-15 14:30:20 IST
2020-01-15 14:30:35.600 IST [10854] LOG:  database system is ready to accept connections
 done
server started
`
So, anyway i started using termux for database server and termux arch for PHP & Apache.

**Comment by abicorios** [comment]
Also, some info about https://wiki.termux.com/wiki/Postgresql

**Comment by T4P4N** [comment]
@abicorios thank you very much :)
