### ISSUE TITLE
How to install LXDE

### ISSUE THREAD

**Issue by JanuszChmiel** [sdrausty/termux-archlinux#17]
Dear specialists,
I would like to install LXDE desktop environment. I have successfully go through all setup steps of Archlinux Bash script for Termux. I have issue, that I do not know, how to install LXDE.
When I Am loggedas root user and when I type
pacman -S lxde
System is giving Me several questions and I do not know, which numbers should I choose.
Is this project under development, so many packages are specially modified to be compatible with Termux, so for now,there is no stable LXDE desktopenvironment?
I have tried several choices, but I have got message aboutconflicting packages. By other words, system did not simply install LXDE automatically.
Because LXDE is The onlyone stable GTk desktop environment which can run in Proot without issues, I would like to install it.
I Am also helpless to install Firefox. I Am working with ARM 32 BIT system with 32 BIT ARM CPU. I Am using Android 6.1.
Some packages can be simply installed. But some not.
Any instructions will be very welcomed.
I know, that I can not run startx to run installed desktop environment, Iwill tryXserver XSDL instead.
I also do not have problems to run separate apps without whole desktop environment.
Thank you very much for yours help.
With kindness regards.
Janusz Chmiel

**Comment by sdrausty** [comment]
@JanuszChmiel we have discussed this here https://github.com/sdrausty/TermuxArch/issues/59 and here https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+LXDE.

**Comment by sdrausty** [comment]
You are welcome to share here and at the links I have shared @JanuszChmiel.
