### ISSUE TITLE
git cannot clone https

### ISSUE THREAD

**Issue by dlintw** [sdrausty/termux-archlinux#18]
after Pacman -Syu, git can Not work for HTTPS.
I am wonder does it caused by upstream

**Comment by sdrausty** [comment]
@dlintw this appears to be an error of unknown origin.
> fatal: cannot fstat packfile: Operation not permitted
fatal: index-pack failed

I got this error initially on armv7.  However, upon further testing, I could not reproduce it on armv8.  Furthermore, this error has also disappeared on the armv7 device, and git clone works.

Try cloning again. Do the error still persist?
