### ISSUE TITLE
lets bring secure way howto run Xorg directly on nonrooted Android device 

### ISSUE THREAD

**Issue by JanuszChmiel** [sdrausty/termux-archlinux#19]
May be, that my plea is rather developers science fiction, but I would like to please alladvanced developers here, if somebody of us know about secure way how to use Xorg with no need to use Xserver XSDL or VNC on non rooted devices.
Because it would be perfect, if XORG could be used directly.
Or really, this is not possible if Android device have not been rooted?
What do you think about this approach on this forum thread?
https://forum.xda-developers.com/showpost.php?p=35205246
Or also this .so driver require rooted Android?
Thank you very much

**Comment by sdrausty** [comment]
@JanuszChmiel rooting breaks all the security features of the OS.  Can you please elaborate on the topic of this issue.
