### ISSUE TITLE
Arch setup script can not finish its installation 

### ISSUE THREAD

**Issue by JanuszChmiel** [sdrausty/termux-archlinux#20]
Dear specialists,
I Am running yours script on Lenovo TAB 3 8. Build in algorithms autodetect used architecture as ARM64. But after extraction, I AM getting following errors.
Bash script output is attached. Unfortunately, I do not know how to set more lines on console so I could attach whole output.
I Am running latest Termux from Google Play, I have applied latest updates for Termux.
I have no issues with yours script when running on Blackview A5. I could even run Orca screen reader, pulseaudio-alsa and Seamonkey WEB browser without severe crasheven on this cheap mobile phone.
I Am wondering, what is wrong on my tablet, which have better performance.
I can try to disable my antivirus service which uses Google accessibility service to run.
But I do not know if this will help.
If you know about something, which I could do to finish The installation, please let Me know.

**Comment by JanuszChmiel** [comment]
My tablet have big problem. Lenovo manufacturers have strictly enabled security feature encrypt my tablet and I can not disable this function. Other devices offer users to turn this feature off, even it allocates many energy and it can take several hours during tablet decryption. So may be, that this build in real time encryption interferes with pacman-key --init'
But I do not know how to securely enforce my tablet to decrypt data and turn this feature off.

**Comment by sdrausty** [comment]
It will be nice if more Lenvo users share here.  I don't own a Lenvo.  Can you please share `setupTermuxArch.sh sysinfo` here @JanuszChmiel?

**Comment by JanuszChmiel** [comment]
Here is .log file which I Am attaching. Thank you very much for yours cooperation. I hope, that Theproblem is not causedby The tablet encryption which can not be disabled from Android settings.
