### ISSUE TITLE
error while starting termuxArch

### ISSUE THREAD

**Issue by Eslamsk** [sdrausty/termux-archlinux#23]
$ ./startarch
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/arch, cwd = /data/data/com.termux/files/home/arch, $PATH=(null))
fatal error: see `proot --help`.

![screenshot_20190114-144839](https://user-images.githubusercontent.com/41478669/51114265-69ca0700-180d-11e9-901b-6cd41bd65a0e.jpg)

**Comment by sdrausty** [comment]
@Eslamsk can you share `setupTermuxArch.sh sysinfo` information?
