### ISSUE TITLE
No webbrowser works. AT ALL

### ISSUE THREAD

**Issue by Merith-TK** [sdrausty/termux-archlinux#25]
Sofar, the browsers that launch are below
`Firefox`: White screen, nothing else
`midori`: Loads UI, but returns error `failed to create shared memory file /WK2SharedMemory.<randome numbers>: Permission Denied` ∞'ly
`Surf`: White Screen, returns `failed to create shared memory file /WK2SharedMemory.<randome numbers>: Permission Denied` ∞'ly

Browsers that dont launch for me
`Chromium`: Literally nothing happens, havent gotten terminal output yet (tablet is dead)

`libandroid-shmem` has been installed in Termux,
No root is obtainable at this time. (as in, Android Root)

Going to test a fresh install (Fresh Termux and Fresh Termux-Arch)

**Comment by sdrausty** [comment]
@Merith-TK many browsers do work with Arch Linux in Termux PRoot https://github.com/sdrausty/TermuxArch/issues?utf8=✓&q=is%3Aissue+browser

> `libandroid-shmem` has been installed in Termux,

Can you please outline the details used to install it?

**Comment by Merith-TK** [comment]
Give me a short bit, 
`libandroid-shmem` was installed via `pkg install libandroid-shmem`

Currently in progress of reinstalling Termux-Arch on my tablet. (vnc is giving me headaches but i know its user error)

**Comment by Merith-TK** [comment]
Give me a short bit, 
`libandroid-shmem` was installed via `pkg install libandroid-shmem`

Currently in progress of reinstalling Termux-Arch on my tablet. (vnc is giving me headaches but i know its user error)

**Comment by JKGrandmaster** [comment]
"pkg install firefox" Inside desktop os open os terminal with out root pkg  install firefox
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://mirrors.bfsu.edu.cn/termux/apt/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libnspr libnss
The following NEW packages will be installed:
  firefox libnspr libnss
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 49.2 MB of archives.
After this operation, 210 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://packages-cf.termux.dev/apt/termux-x11 x11/main aarch64 firefox aarch64 118.0.1 [47.2 MB]
Get:2 https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable/main aarch64 libnspr aarch64 4.35 [183 kB]
Get:3 https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable/main aarch64 libnss aarch64 3.93 [1843 kB]
Fetched 49.2 MB in 1min 59s (415 kB/s)                                         
Selecting previously unselected package libnspr.
(Reading database ... 57701 files and directories currently installed.)
Preparing to unpack .../libnspr_4.35_aarch64.deb ...
Unpacking libnspr (4.35) ...
Selecting previously unselected package libnss.
Preparing to unpack .../libnss_3.93_aarch64.deb ...
Unpacking libnss (3.93) ...
Selecting previously unselected package firefox.
Preparing to unpack .../firefox_118.0.1_aarch64.deb ...
Unpacking firefox (118.0.1) ...
Setting up libnspr (4.35) ...
Setting up libnss (3.93) ...
Setting up firefox (118.0.1) ...
Processing triggers for desktop-file-utils (0.26-7) ...
~ $
