### ISSUE TITLE
failed to synchronize all databases

### ISSUE THREAD

**Issue by remo7777** [sdrausty/termux-archlinux#26]
![screenshot_20190306-141238](https://user-images.githubusercontent.com/28594846/53867610-3be98d80-401a-11e9-9db7-0ba8c39b2a1f.jpeg)

**Comment by KevinBlue18** [comment]
This is the wrong repo. The main repo is [TermuxArch](https://github.com/sdrausty/TermuxArch)

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues/86

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues/119
