### ISSUE TITLE
Start Arch command at boot

### ISSUE THREAD

**Issue by ToRvaLDz** [sdrausty/termux-archlinux#27]
I'm trying to start an arch application at boot with termux-boot, the same application run if started out of arch.

The command i run is:
startarch -c "mosquitto" 

I tried also with full path without success, any suggestion? Tnx

**Comment by hugocornago** [comment]
First, go to this path:
/data/data/com.termux/files/usr/etc
Then edit this file:
bash.bashrc
(I use vim editor)
It should view like this:

command_not_found_handle() {
        /data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
}

PS1='\$ '

Just add the command at the bottom

command_not_found_handle() {
        /data/data/com.termux/files/usr/libexec/termux/command-not-found "$1"
}

PS1='\$ '
startarch -c "python"

Just reopen termux.

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+chsh
