### ISSUE TITLE
how to uninstall archlinux？

### ISSUE THREAD

**Issue by Asutorufa** [sdrausty/termux-archlinux#3]
how to uninstall archlinux？

**Comment by sdrausty** [comment]
To uninstall, use `bash setupTermuxArch.sh --purge`.  `bash setupTermuxArch.sh --help` has more information.

**Comment by Asutorufa** [comment]
thank you

**Comment by Etzio-TUI** [comment]
Everytime I attempt the above command, i get "No command setup found, did you mean: Command setcap in package libcap; Command dmsetup in package libdevmapper from the root-repo repository.  I'm so confused trying to get this to work, I just want to get rid of it. When I run "ls" i see TermuxArch along with other things i.e. "awk' "rev" "storage" "uname" "md5sum" "sha512sum" "tar". When I run setup TermuxArch.sh, I get "No  command found". Please can someone help me understand this so I can keep working to learn this?

**Comment by SDRausty** [comment]
> When I run setup TermuxArch.sh, I get "No command found". Please can someone help me understand this so I can keep working to learn this?

Try `bash setupTermuxArch` to setup Arch Linux in Termux PRoot on Android, and `bash setupTermuxArch help` for help.
