### ISSUE TITLE
passwd is not hiding password entry

### ISSUE THREAD

**Issue by chubbson** [sdrausty/termux-archlinux#30]
not sure where this problem is caused from.
termux before i start startarch:
passwd works as mentioned, password which i enter will not be shown on keyentry.
when i start arch with startarch.sh
passwd will show any charactor which i enter.

i tried also in arch ssh-keygen which will prompt also for password entry, that workes fine . doesnt show any key entry.

really not sure if it is a termux-archlinux issue.

**Comment by KevinBlue18** [comment]
This is the wrong repo. The main repo is [TermuxArch](https://github.com/sdrausty/TermuxArch)

**Comment by chubbson** [comment]
Ty, opened a new Issue https://github.com/sdrausty/TermuxArch/issues/170
