### ISSUE TITLE
Running a command with root

### ISSUE THREAD

**Issue by xCuri0** [sdrausty/termux-archlinux#31]
I need root for using aircrack-ng (I have manually patched the kernel for it so it should work) but sudo won't give me root access

**Comment by KevinBlue18** [comment]
This is the wrong repo. The main repo is [TermuxArch](https://github.com/sdrausty/TermuxArch)

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues/38

**Comment by xCuri0** [comment]
@sdrausty I already get root user in startarch when but I try to use stuff that require root like aircrack-ng it says permission denied
