### ISSUE TITLE
Checksum fail 

### ISSUE THREAD

**Issue by happytommyl** [SDRausty/termux-archlinux#35]
 bash setupTermuxArch.sh

 🕛 > 🕛 ＴｅｒｍｕｘＡｒｃｈ v1.6.7.id5677 shall attemp
t to install Linux in /data/data/com.termux/files/home/a
rch.  Arch Linux in Termux PRoot shall be available upon
 successful completion.  To run this BASH script again,
use `!!`.  Ensure background data is not restricted.  Ch
eck the wireless connection if you do not see one o'cloc
k 🕐 below.  Checking prerequisites…

Found download tool `curl`; Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

  % Total    % Received % Xferd  Average Speed   Time
 Time     Time  Current
                                 Dload  Upload   Total
 Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -
  0     0    0     0    0     0      0      0 --:--:-- -
100   153  100   153    0     0    102      0  0:00:01
100   153  100   153    0     0    102      0  0:00:01
0:00:01 --:--:--   102
100 35597  100 35597    0     0  51815      0 --:--:-- -
-:--:-- --:--:-- 51815

setupTermuxArch.sh: line 58: /data/data/com.termux/files
/usr/bin/applets/sha512sum: No such file or directory

 🔆 WARNING sha512sum mismatch!  Setup initialization mi
smatch!   Try again, initialization was not successful t
his time.  Wait a little while.  Then run `bash setupTer
muxArch.sh` again…

setupTermuxArch.sh  v1.6.7.id5677: DONE 🏁

**Comment by SDRausty** [comment]
@happytommyl for some reason, you don't have this  /data/data/com.termux/files
/usr/bin/applets/sha512sum file.  You can create it manually by symlinking to BusyBox.  It is installed by default.  Any idea why it is missing from your system?

**Comment by SDRausty** [comment]
@happytommyl I checked to see if there is any error:
![Screenshot_20190726-105805](https://user-images.githubusercontent.com/27742457/61961794-27d90500-af96-11e9-8ad9-4becfbd335e9.png)

**Comment by SDRausty** [comment]
@happytommyl I checked to see if there are any errors:
![Screenshot_20190726-105805](https://user-images.githubusercontent.com/27742457/61961794-27d90500-af96-11e9-8ad9-4becfbd335e9.png)

**Comment by SDRausty** [comment]
@happytommyl for some reason, you don't have this  /data/data/com.termux/files
/usr/bin/applets/sha512sum file.  You can create it manually by symlinking to /data/data/com.termux/files/usr/bin/busybox.  It is installed by default.  Any idea why the symlink sha512sum is missing from this system?

**Comment by jeffrey562** [comment]
Had to symlink three different things (two more after the one you suggested). Then was met with this [message](https://i.imgur.com/R4doJIu.jpg). Any idea what's going on?

**Comment by mpolidori** [comment]
@jeffrey562 I ran into the same error after the 3 symlinks. Were you able to resolve this?

**Comment by jeffrey562** [comment]
@mpolidori unfortunately, I was not. I'm about ready to give up on this, but I guess at the very least I should report this issue as something on its own instead of dragging it on in this closed thread.

**Comment by SDRausty** [comment]
This symlink comes from busybox.  As this is a Termux package, busybox issues are https://github.com/termux/termux-packages/issues at this link.

**Comment by SDRausty** [comment]
> Any idea why the symlink sha512sum is missing?  

> You can create it manually by symlinking to $PREFIX/bin/busybox.

**Comment by SDRausty** [comment]
> You can create sha512sum manually by symlinking to $PREFIX/bin/busybox:

```
cd $PREFIX/bin/applets/
ln -s ../busybox sha512sum
```

> Any idea why the symlink sha512sum is missing?  

This symlink comes from busybox.  As busybox is a Termux package, busybox issues are at https://github.com/termux/termux-packages/issues this link.

**Comment by SDRausty** [comment]
@happytommyl @jeffrey562 @mpolidori what is the output of `ls $PREFIX/bin/applets/`?

**Comment by mpolidori** [comment]
```
ls $PREFIX/bin/applets
crond    hostname  mpstat  runsvdir           tar     which
crontab  inotifyd  mv      sendmail           tcpsvd
diff     iostat    nmeter  sha512sum          uname
ftpd     lsof      rm      start-stop-daemon  uptime
ftpget   lsusb     rmdir   sv                 usleep
ftpput   md5sum    runsv   svlogd             vi
```

This is after I created the symlinks for sha512sum, tar, uname, and md5sum. Before that those were missing.

**Comment by jeffrey562** [comment]
@SDRausty https://i.imgur.com/oOtxGgB.jpg

Also after I manually symlinked three things. I don't remember the other two after sha512sum, but it's probably the same as the ones mpolidori mentioned.

**Comment by SDRausty** [comment]
Here's the correct output:
```
$ ls $PREFIX/bin/applets/
ar                 fuser              pipe_progress      sv
arp                getopt             pkill              svlogd
awk                grep               pmap               sync
base64             gunzip             popmaildir         sysctl
basename           gzip               printenv           tac
bbconfig           hd                 printf             tail
bunzip2            head               ps                 tar
bzip2              hexdump            pscan              tcpsvd
cal                hostname           pstree             tee
cat                httpd              pwd                telnet
chattr             id                 pwdx               telnetd
chgrp              ifconfig           readlink           test
chmod              inotifyd           realpath           tftp
chown              install            reformime          tftpd
chpst              iostat             renice             time
chrt               ipcalc             reset              timeout
cksum              kill               resize             touch
clear              killall            rev                tr
cmp                less               rm                 true
comm               linux32            rmdir              tty
cp                 linux64            route              ttysize
cpio               ln                 run-parts          udpsvd
crond              ls                 runsv              uname
crontab            lsattr             runsvdir           uncompress
cut                lsof               rx                 unexpand
date               lsusb              script             uniq
dc                 lzma               scriptreplay       unix2dos
dd                 makemime           sed                unlink
diff               md5sum             sendmail           unlzma
dirname            mkdir              seq                unxz
dos2unix           mkfifo             setsid             unzip
du                 mknod              setuidgid          uptime
echo               mktemp             sha1sum            usleep
egrep              more               sha256sum          uudecode
env                mpstat             sha3sum            uuencode
envdir             mv                 sha512sum          vi
expand             nc                 shuf               watch
expr               netstat            sleep              wc
false              nice               smemcap            wget
find               nmeter             softlimit          which
fold               nohup              sort               whoami
free               nproc              split              whois
fsync              od                 start-stop-daemon  xargs
ftpd               patch              strings            xz
ftpget             pgrep              stty               yes
ftpput             pidof              sum
```
```
$ $PREFIX/bin/busybox --install
busybox: /bin/ar: No such file or directory
busybox: /sbin/arp: Permission denied
busybox: /bin/awk: No such file or directory
busybox: /bin/base64: No such file or directory
busybox: /bin/basename: No such file or directory
busybox: /bin/bbconfig: No such file or directory
busybox: /bin/bunzip2: No such file or directory
busybox: /bin/bzip2: No such file or directory
busybox: /bin/cal: No such file or directory
busybox: /bin/cat: No such file or directory
busybox: /bin/chattr: No such file or directory
.
.
.
```

The `busybox --install` feature appears to be broken.  Please let https://github.com/termux/termux-packages/issues know about these errors.  It also appears that linking libraries in Termux is broken at present too.

**Comment by SDRausty** [comment]
Evidently backward comparability is being broken in Termux:
1. https://github.com/termux/termux-packages/issues/4123
2. https://github.com/termux/termux-packages/issues/4128
  * https://github.com/termux/termux-packages/issues/4128#issuecomment-516894201
  > Busybox is getting deprecated and will no longer provide symlinks. 

Breaking backward compatibility is something programmers should avoid, especially when distributing a stable release.  Please inform https://github.com/termux/termux-packages/issues/ of this fact.  As:
```
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```
`bin` takes presidence over `bin/applets` there is NO VALID REASON to break comparability in Termux.

**Comment by SDRausty** [comment]
Evidently backward compatibility is being broken in Termux:
1. https://github.com/termux/termux-packages/issues/4123
2. https://github.com/termux/termux-packages/issues/4128
  * https://github.com/termux/termux-packages/issues/4128#issuecomment-516894201
  > Busybox is getting deprecated and will no longer provide symlinks. 

Breaking backward compatibility is something programmers should avoid, especially when distributing a stable release.  Please inform https://github.com/termux/termux-packages/issues/ of this fact.  As:
```
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```
`bin` takes presidence over `bin/applets` there is NO VALID REASON to break compatibility in Termux.

**Comment by SDRausty** [comment]
You can create sha512sum manually by symlinking to $PREFIX/bin/busybox:
```
cd $PREFIX/bin/applets/
ln -s ../busybox sha512sum
au bsdtar
```

These steps should resolve the issue for the time being.  If there are other 🚶 steps, please share.  

[au](https://sdrausty.github.io/au/)

**Comment by victoryang00** [comment]
no solutions

**Comment by ogahozy** [comment]
No success  after many attempt:
🔆 WARNING: Maximum amount of attempts exceeded!  Run `bash setupTermuxArch.sh` again.  See `bash setupTermuxArch.sh help` to resolve download errors.  If this keeps repeating, copy `knownconfigurations.sh` to `setupTermuxArchConfigs.sh` with preferred mirror.  After editing `setupTermuxArchConfigs.sh`, run `bash setupTermuxArch.sh` and `setupTermuxArchConfigs.sh` loads automaticaly from the same directory.  Change mirror to desired geographic location to resolve md5sum errors.

User configurable variables are in `setupTermuxArchConfigs.sh`.  Create this file from `kownconfigurations.sh` in the working directory.  Use `bash setupTermuxArch.sh manual` to create and edit `setupTermuxArchConfigs.sh`.

        Run `bash setupTermuxArch.sh` again…

**Comment by SDRausty** [comment]
$ bash setupTermuxArch.sh s

Setting mode to sysinfo.

 🕛 > 🕛 TermuxArch v1.6.7.id5677 shall create a system information file.
Ensure background data is not restricted.  Run bash setupTermuxArch.sh help
for additional information.  Check the wireless connection if you do not
see one o'clock 🕐 below.  Checking prerequisites…

Found download tool `curl`; Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

  % Total    % Received % Xferd  Average Speed   Time    Time     Time
Current
                                 Dload  Upload   Total   Spent    Left
Speed
100   153  100   153    0     0     49      0  0:00:03  0:00:03 --:--:--
49
100 35597  100 35597    0     0  25945      0  0:00:01  0:00:01 --:--:--
19692

 🕛 > 🕐 TermuxArch download: OK

CANNOT LINK EXECUTABLE "proot": library "libtalloc.so.2" not found

 TermuxArch WARNING:  Generated script signal 1 near or at line number 600
by `trap`!

setupTermuxArch.sh s v1.6.7.id5677: [Exit Signal 201] DONE 🏁

**Comment by ogahozy** [comment]
how do i get it up and runing.
how can install it manually. 
🕛 > 🕞 Contacting worldwide mirror https://os.archlinuxarm.org: DONE

.  If contact with the local mirror is not successful, run bash setupTermuxArch.sh again.  Should the worldwide mirror not provide another geographically nearby server after a couple of attempts, use bash setupTermuxArch.sh manual after locating a local mirror from the Internet; See bash setupTermuxArch.sh help for additional options.  Download of ArchLinuxARM-aarch64-latest.tar.gz pending Internet connection:

**Comment by ogahozy** [comment]
i have this when i run the system info;
$ bash setupTermuxArch.sh sysinfo

Setting mode to sysinfo.

 🕛 > 🕛 TermuxArch v1.6.7.id5677 shall create a system information file.  Ensure background data is not restricted.  Run bash setupTermuxArch.sh help for additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Found download tool `curl`; Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com
curl: (6) Could not resolve host: raw.githubusercontent.com

 TermuxArch WARNING:  Generated script signal 6 near or at line number 600 by `trap`!

**Comment by SDRausty** [comment]
Steps to reproduce:
`CANNOT LINK EXECUTABLE "proot": library "libtalloc.so.2" not found`
AND
`E: Unable to locate package proot`

Install https://f-droid.org/repo/com.termux_74.apk
Run  https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.sh

   * https://github.com/termux/termux-app/issues
   * https://github.com/termux/termux-packages/issues
   * https://github.com/termux/proot/issues

**Comment by SDRausty** [comment]
Steps to reproduce `CANNOT LINK EXECUTABLE "proot": library "libtalloc.so.2" not found` and `E: Unable to locate package proot` are to fresh install https://f-droid.org/repo/com.termux_74.apk on a fresh device, and to run  https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.sh Issues can be raised at the following:

   * https://github.com/termux/termux-app/issues
   * https://github.com/termux/termux-packages/issues
   * https://github.com/termux/proot/issues
   * https://github.com/TermuxArch/TermuxArch/issues

**Comment by SDRausty** [comment]
> E: Unable to locate package proot
TermuxArch WARNING: Generated script signal 100 near or at line number 600 by trap!

setupTermuxArch.sh v1.6.7.id5677: [Exit Signal 201] DONE checkered_flag

![Screenshot_20190903-221031](https://user-images.githubusercontent.com/27742457/64220545-c0b54700-ce97-11e9-81a4-4821dd350f44.png)

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/4406e856ce30af50d25ccb7f4c9a480a4c1293bf removes hardcoded paths.  

 ##### -rwxrwx--- [setupTermuxArch.bash](https://TermuxArch.github.io/TermuxArch/setupTermuxArch.bash) 
##### -r--r--r-- [setupTermuxArch.bash](https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.bash)

If you get errors with `tar`, use `bsdtar`

**Comment by imShara** [comment]
@SDRausty and now

🕛 > 🕜 TermuxArch v2.0.id0403 integrity: OK
necessaryfunctions.bash: line 106: /data/data/com.termux/files/usr/bin/applets/uname: No such file or directory

**Comment by SDRausty** [comment]
@imShara thank you for bringing this to my attention!

**Comment by imShara** [comment]
Actually there was more errors while installation. I will write how I solve it if updated version still not final

**Comment by SDRausty** [comment]
https://github.com/SDRausty/TermuxArch/releases/tag/v2.0.id0406
