### ISSUE TITLE
can't install arch linux on my A50 

### ISSUE THREAD

**Issue by foodmaher** [SDRausty/termux-archlinux#36]
When you try to install the Arch Linux, you show me this problem and do not know how to solve it.

![Screenshot_20190805-161413_Termux](https://user-images.githubusercontent.com/27397889/62467550-b28ee080-b79c-11e9-83fa-3f720710908f.jpg)

Kernel Device: 4-14-62
Android version: 9.0 pie
Termux version: last version

**Comment by SDRausty** [comment]
@foodmaher see https://github.com/SDRausty/TermuxArch/issues/179#issuecomment-517108066

**Comment by foodmaher** [comment]
> @foodmaher see [SDRausty/TermuxArch#179 (comment)](https://github.com/SDRausty/TermuxArch/issues/179#issuecomment-517108066)

I followed instructions but a new problem appeared
![Screenshot_20190806-124036_Termux](https://user-images.githubusercontent.com/27397889/62529632-a7dd5580-b847-11e9-8407-f28bd3c0e096.jpg)

**Comment by foodmaher** [comment]
@SDRausty

you forgot : `ln -s ../busybox md5sum`

**Comment by foodmaher** [comment]
I closed the issue ...
