### ISSUE TITLE
How does this project rename Termux sessions?

### ISSUE THREAD

**Issue by sudomain** [SDRausty/termux-archlinux#37]
Not really an issue with the project, but this is the only medium I know of to contact @SDRausty .How does this project rename Termux sessions programatically? as seen in the following screenshot:

![Screenshot_2019-09-02-19-31-14](https://user-images.githubusercontent.com/30786326/64135636-5d081c80-cdb8-11e9-88e2-6d78a7ee37f7.png)

**Comment by xixian2106** [comment]
Here you go.


# the source code
https://github.com/SDRausty/termux-archlinux/blob/c02f86f6c8feb20210529c83273d1c9ec31afa82/scripts/files/cache0/setupTermuxArch.sh#L601
so, you can change the name of a termux session through run the follow command:

```bash
printf '\033]2;Hello, world!\a'
```


# printf
about `printf`, reference [printf(1)](http://man7.org/linux/man-pages/man1/printf.1.html)
parts of [printf(1)](http://man7.org/linux/man-pages/man1/printf.1.html):

```
\a     alert (BEL)
\NNN   byte with octal value NNN (1 to 3 digits)
\uHHHH Unicode (ISO/IEC 10646) character with hex value HHHH (4 digits)
```


# \033]2
about `\033]2`, reference [Input Translation](https://www.gnu.org/software/screen/manual/html_node/Input-Translation.html) or [Cursor Movement](http://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html).
a part of [Input Translation](https://www.gnu.org/software/screen/manual/html_node/Input-Translation.html):

```
Key name        Termcap name    Command
-----------------------------------------------------
Insert               kI         stuff \033[2~
```

# \007
about `\007`, reference [7-bit ASCII Character Codes](https://www.sciencebuddies.org/science-fair-projects/references/ascii-table).
a part of [7-bit ASCII Character Codes](https://www.sciencebuddies.org/science-fair-projects/references/ascii-table):

Decimal | Octal | Hex | Binary | Value | Description
| - | - | - | - | - | - |
007 | 007 | 07 | 0000 0111 | BEL | bell

You could do a search for more detail.

**Comment by andhie76** [comment]
Testimoni
