### ISSUE TITLE
Can we use it with root access?

### ISSUE THREAD

**Issue by imShara** [SDRausty/termux-archlinux#39]
I need low level access from termux-archlinux to run `ip link set`. Is it possible?

**Comment by SDRausty** [comment]
@imShara >  need low level access from termux-archlinux to run 

Using PRoot in a cracked/rooted environment is beyond scope of this project.  See whether building APKs https://github.com/BuildAPKs with appropriate permissions helps in resolving access to device abilities.  Alternatively, you can build Android https://wiki.archlinux.org/index.php/Android :sweat_smile:

**Comment by imShara** [comment]
It's solves easily — [tsu](https://github.com/cswl/tsu)

`tsu startarch`
