### ISSUE TITLE
HUAWEI Mate 10 lite and Archlinux setup script error

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#41]
Please does somebody of us know, if Android kernel of this device is capable to run Termux and especially Proot and some Linux distribution by using this Termux module?
Because I can not use Linux distro from Termux on this device. I AM always getting some bugs. Warning that some symbolic link have been changed from 6 to 8, Yours setup script can not find packages name which it require and I AM using latest stable Termux no BETA. Or all of you, creators of Debian scripts and Arch Linux script have made many changes so errors will exist on every device?
Now, setup script is writing The following error.
E: Enable to locate package bsddar 
Termux arch Warning: generated script signal 100 near or ad line number 615
Is it error of script, or really somy hydden kernel issue of my phone?
Thank you very much for yours answer.
Or should I add some other repository to Termux to get it work?

**Comment by SDRausty** [comment]
> Or should I add some other repository to Termux to get it work?

`setupTermuxArch.bash` is all that should be required.

> Proot and some Linux distribution by using this Termux module?
Because I can not use Linux distro from Termux on this device. I AM always getting some bugs. Warning that some symbolic link have been changed from 6 to 8, Yours setup script can not find packages name which it require and I AM using latest stable Termux no BETA. Or all of you, creators of Debian scripts and Arch Linux script have made many changes so errors will exist on every device?

@JanuszChmiel can you post output from: `setupTermuxArch.bash sysinfo`?

**Comment by SDRausty** [comment]
> Or should I add some other repository to Termux to get it work?

`setupTermuxArch.bash` is all that is wanted, as it should install everything that is required.

> Proot and some Linux distribution by using this Termux module?
Because I can not use Linux distro from Termux on this device. I AM always getting some bugs. Warning that some symbolic link have been changed from 6 to 8, Yours setup script can not find packages name which it require and I AM using latest stable Termux no BETA. Or all of you, creators of Debian scripts and Arch Linux script have made many changes so errors will exist on every device?

@JanuszChmiel can you post output from: `setupTermuxArch.bash sysinfo` please?

**Comment by SDRausty** [comment]
@JanuszChmiel in regards to ` android.jar ` see https://github.com/BuildAPKs/buildAPKs/issues/3 for any progress.

**Comment by JanuszChmiel** [comment]
Yes, with pleasure. I will use my Android accessibility feature copy last message to clipboard and I will transfer message with clipboard. May be, that there would be even some special Bash solution so message which have been printed by yours command could be automatically placed to ascii file on my favourite Android device location Downloads.
I will also run yours script on other device.

**Comment by JanuszChmiel** [comment]
I have executed
bash a.bash sysinfo
I have executed from storage/Downloads
But error do not allow to get system information

s connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Found download tool `curl`: Continuing…

information file.  Ensure background data is not restricted.  Run bash setupTermuxArch.bash help for additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…
Found download tool `curl`: Continuing…
                                                Installing bsdtar…

Reading package lists3krát tečka﻿ Done
Building dependency tree
Reading state information3krát tečka﻿ Done
E: Unable to locate package bsdtar

TermuxArch WARNING:  Generated script signal 100 near or at line number 615 by `trap`!

**Comment by JanuszChmiel** [comment]
I think, that The error is caused By The fact, that Termux repository for Android 7.0 do not contain The bsdtar package.
So can I try to manually install .deb package of bsdtar for older Android Termux release, or it will cause AN crash, because older binary will not work with Termux which support Android 7.0?
I have full potential to even grab exact installation outputs, so if You have AN idea and if you have some time to help Me to debug with you, I Am really ready to cooperate.
If Huavei uses some top secret techniques, which prevent Proot to work correctly and coorecting is out of The possibility of opensource programmers, I will respect it and I will not intrude you with this issue.
I have analysed one developers debate when some professional Userland developer have modified The Proot source code, because one model of Huavei used kernel version, which have used some kernel function in The way, that Proot specific function could not work, so The Userland engaged developer have made AN work around. The question is, if it is always possible to safely develop such complex work arounds inside Proot source code and if it is problem between Kernel and Proot, or if other Huavei higher level build in Android service make somethink unsoft so users can not use Linux distribution by using Proot at all.
Really, there is some difference between Lenovo Tab 3 8 and Android 6.0. Because Debian work perfectly, yours Archlinux script fail to work thanks to build in encryption key generator, which is very probably do not work because Lenovo have enabled Tablet encryption in The security settings and this checkbox can not be unchecked. Encryption is enabled by default and factory reset do not disable it, it is build in feature.
Any discussion and help is very welcomed, I Am really ready to think about The problem with you and I Am ready to test.
I can not root my phone, because custom ROMS often lacks The support of reliable and stable kernel drivers for build in chips for BLuetooth, sound chip and as A blind user, I Am dependon reliable and stable system.

**Comment by JanuszChmiel** [comment]
Here is log produced by The sysinfo script command line option.
[setupTermuxArchSysInfo7cf5.log](https://github.com/SDRausty/termux-archlinux/files/3911758/setupTermuxArchSysInfo7cf5.log)

**Comment by SDRausty** [comment]
> Here is log produced by The sysinfo script command line option.

Recieved; Thank you

**Comment by SDRausty** [comment]
> Unable to locate package bsdtar

` bsdtar ` for aarch64 architecture is available http://termux.net/dists/stable/main/binary-aarch64/bsdtar_3.4.0-1_aarch64.deb here.  

` curl -OL http://termux.net/dists/stable/main/binary-aarch64/bsdtar_3.4.0-1_aarch64.deb ` will transfer it to device.  ` dpkg -i bsdtar_3.4.0-1_aarch64.deb ` should state which dependencies are needed.  

Download and install them first.  Then run ` dpkg -i bsdtar_3.4.0-1_aarch64.deb ` again.  If the manual install goes well,  ` bsdtar ` will be at your command.

**Comment by SDRausty** [comment]
> prevent Proot to work correctly
> Debian work perfectly

How do you run debian if proot does not work correctly?

**Comment by JanuszChmiel** [comment]
Debian run on my Lenovo 38 tablet. Here work perfectly. But on Huavei, I Am getting other error related .so library load.
I have filled out stand alone issue on The Debiasn script Github page.
I AM very sorry for my chaos. I have finally attached sysinfo log. I hope, that it will not show some info, that Huavei kernel block some important folders or files.

**Comment by SDRausty** [comment]
> The question is, if it is always possible to safely develop such complex work arounds inside Proot source code

> cannot root my phone

Both these concerns are also being addressed here at https://github.com/BuildAPKs as developing APKs does not require root and proot.  APKs can be granted many Android permissions.  Having the source code to the applications seems like a better path to follow.

**Comment by SDRausty** [comment]
> ready to cooperate

When you post,  @JanuszChmiel can you please double space your paragraphs.  This should make your thought easier to follow.

**Comment by SDRausty** [comment]
> error related .so library

Unfortunatly, I have been receiving more of these errors in Termux recently too.  

> I have filled out stand alone issue

Are you referring to this https://github.com/termux/proot/issues/48 issue?

**Comment by JanuszChmiel** [comment]
Yes, I will try to split my comments in to paragraphs. I will press Enter twice above every important point. Thank you for yours good remark.


Because I have finally completed dropbear setup, I can use Windows computer to store console screens output. Because screen readers can always only fetch output from The last visible screen.
Fortunately, Putty for Windows allows logging, so output will be usable. I have chosen printable output protocol format.

**Comment by SDRausty** [comment]
In reference to your question here at https://github.com/termux/proot/issues/50 Can Proot be used to access Linux distribution from external storage such as SD card #50

https://github.com/TermuxArch/TermuxArch/issues/3 Can Proot be used to access a Linux distribution from external storage such as an SD card? #3

**Comment by SDRausty** [comment]
> getting other error related .so library load

Can you share the output of the error please?  It is `CANNOT LINK EXECUTABLE...`?

**Comment by JanuszChmiel** [comment]
For Yours script, I Am getting much different errors. I will add separate big log to analyse for you. Errors start when The integrity of downloaded archive will be verified.
I will add protocol as soon as possible.

**Comment by JanuszChmiel** [comment]
Here is The whole log.

[ArchLinux.log](https://github.com/SDRausty/termux-archlinux/files/3913010/ArchLinux.log)

**Comment by JanuszChmiel** [comment]
I have one important notice.
I Am getting warning related to The fact, that symlink have been changed from 6 to 8 even when using clean Termux environment without Proot and even when not running Linux distribution by using Proot. It is normal Termux behaviour? Or it is warning, that some processes on my phone are making something which prevent Me from using Proot and Linux distributions?
When I use even complex apps for Termux which have been prepared by Termux packagers, it work perfectly.

Who of us would give Me a Piece of advice how to obtain The most detailed Proot Debug log while running Arch Linux script or other scripts, so I could send it to Proot developer?
Proot debug protocol is very often full of names of Kernel functions and procedures, which Proot uses and there are many Hexadecimal numbers, so really only Krenel expert and Proot advanced developer can coorectly interpret The protocol and determine, if ther is some error which could be repaired.
I Am afraid, that finding and repairing The error is not in our power, because if there is some hydden complex issue between Proot and Android specific kernel, we had to be patient and we should obtain some advices from Proot developer how to help him to debug.

**Comment by JanuszChmiel** [comment]
OK,
So I will try to do my best to correctly understand, on which line of yours script should i give The proot debug value 9, which is The most deatiled proot debug log output.
proot – v9
So I must add –v 9
somewhere. Or I can even start with more simpler Bash script such as for installing Debian for Example.
Then I will try to open Proot issue on Termux Github area to determine, if it is some chance to repair. it
Because problem is not only specific to yours script, no distro can fully work on my Huavei P10 mate lite model, no matter, which script install it.

**Comment by SDRausty** [comment]
> which line ... should i give ... v9

You can add a line like https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L85 by running `bash setupTermuxArch.bash m[anual] r[efresh]`.   `setupTermuxArch.bash h[elp]` has more information about options.

Alternatively, create a similar line in a *.prs file. See arch/var/binds/fbindexample.prs for more information after installing Arch Linux on device.

> 
> which line ... should i give ... v9

You can add a line like https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L85 by running `bash setupTermuxArch.bash m[anual] r[efresh]`.   `setupTermuxArch.bash h[elp]` has more information about options.

Alternatively, create a similar line in a *.prs file. See arch/var/binds/fbindexample.prs for more information after installing Arch Linux on device.
> który wiersz ... powinienem podać ... v9

Możesz dodać linię taką jak https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L85, uruchamiając `bash setupTermuxArch.bash m[anual] r[efresh]`. `setupTermuxArch.bash h[elp]` ma więcej informacji o opcjach.

Możesz również utworzyć podobną linię w pliku *.prs. Aby uzyskać więcej informacji po zainstalowaniu Arch Linux na urządzeniu, zobacz arch/var/binds/fbindexample.prs.

**Comment by SDRausty** [comment]
> which line ... should i give ... v9

The above instructions work for adding to the proot statement.  To change the verbosity of startarch use ` setupTermuxArch.bash m[anual] r[efresh] ` and change https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L61 to ` PROOTSTMNT="exec proot -v 9 " # The space before the last double quote is necessary.

> który wiersz ... powinienem podać ... v9

Powyższe instrukcje służą do dodawania do instrukcji proot. Aby zmienić gadatliwość startarch, użyj `setupTermuxArch.bash m [anual] r [efresh]` i zmień https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L61 na `PROOTSTMNT =" wykonanie proot -v 9 "# Konieczne jest miejsce przed ostatnim podwójnym cytatem.

**Comment by SDRausty** [comment]
> which line ... should i give ... v9

To change the verbosity of startarch use ` setupTermuxArch.bash m[anual] r[efresh] ` and change https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L61 to ` PROOTSTMNT="exec proot -v 9 " # The space before the last double quote is necessary.

> który wiersz ... powinienem podać ... v9

Aby zmienić gadatliwość startarch, użyj `setupTermuxArch.bash m[anual] r[efresh]` i zmień https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L61 na `PROOTSTMNT =" wykonanie proot -v 9 "# Konieczne jest miejsce przed ostatnim podwójnym cytatem.

**Comment by JanuszChmiel** [comment]
I Am afraid, that I will have problems to run all Linux distributions which uses Proot.
Huavei have decided to configure my file system type so it is case insensitive filesystem. So is package names uses upper case letters in their names, I will not have chance to install them.
If i understand it well. If file system is The case insensitive filesystem, it will not accept upper case letters in file names.
It is very interesting, why developers have decided to create The file system by this way.

But it means, that I must say my dream about running Linux distro on 4 GB of RAm good bye for ever.
