### ISSUE TITLE
AutoStarting via chsh startarch does not work

### ISSUE THREAD

**Issue by lorecast162** [SDRausty/termux-archlinux#42]
Starting termuxArch via startarch manually from termux's bash prompt works fine, but I want it to autostart.

In the guide it was written to do `chsh` and give it `startarch`, so I did that.

When I launch it tho I get this error: `su: user  does not exist` and then it terminates, leaving only the possibility of removing `~/.termux/shell` from a failsafe session.

**Comment by SDRausty** [comment]
> In the guide it was written to do chsh and give it startarch, so I did that.

The guide can be expanded in many ways.  Pull requests can be submitted at https://github.com/TermuxArch/docsTermuxArch/pulls
> leaving only the possibility of...

Have you created this user @lorecast162?  See ` startarch help ` if you have not created a user for Arch Linux in Termux PRoot.

**Comment by SDRausty** [comment]
> want it to autostart.

This information was added last month. Listen to formation should help out with configuring a functioning autostart once again.  The documentation is a little bit out of date; PRs are requested at the documentation websites:

> This link https://github.com/SDRausty/TermuxArch/issues/212 at GitHub has the most current information about setting Arch Linux in Termux PRoot as the default login shell in Termux in your smartphone, tablet, smartTV, wearable and more.  If you choose to, or are simply curious about setting Arch Linux in Termux PRoot as the default login shell, please be well acquainted with safe mode;  Long tapping on NEW SESSION will open a new session in safe mode.  This mode can be used to reset the default shell."
