### ISSUE TITLE
Setup fails with curl error "using bad/illegal format or missing url"

### ISSUE THREAD

**Issue by XDracam** [SDRausty/termux-archlinux#44]
This is what I get when I run the setup script while definitely having internet:

![Screenshot_2019-12-08-04-57-30-968_com termux](https://user-images.githubusercontent.com/30172448/70383979-9e8c0300-1977-11ea-85d1-4828bf129e4f.jpg)

It failed on all `deX` mirrors. I ran this 3 times just to make sure, and the same thing happens every time.

The mirror urls are perfectly accesable from chrome on the same device. 

Looks like a strange curl issue is preventing me from using arch.

**Comment by XDracam** [comment]
More background:
I cloned the repo into ~ and ran `TermuxArch/setup...sh` which caused the error. 

Once I cd'd into the TermuxArch folder and ran `./setup...sh`, everything started working fine.

Adding a proper error message / hint for this case would be a huge QOL benefit (if this is not caused by a bug, that is).

**Comment by SDRausty** [comment]
> Adding a proper error message / hint for this case would be a huge QOL benefit 

Open a https://github.com/TermuxArch/TermuxArch/pulls please.  You can use https://github.com/TermuxArch/TermuxArch/blob/master/scripts/maintenance/tgen.bash to generate the finished product.
