### ISSUE TITLE
can't restore time error

### ISSUE THREAD

**Issue by abinashdash17** [SDRausty/termux-archlinux#46]
i don't know how to fix this error any hint.
![Screenshot_2019-12-30-15-58-48](https://user-images.githubusercontent.com/20315814/71578309-9e69c800-2b1d-11ea-9e21-ba4ac661e1e3.png)

**Comment by SDRausty** [comment]
> can't restore time error 

@abinashdash17 Can you reproduce this error by unpacking the file manually, i.e. `bsdtar -xpf setupTermuxArch.tar.gz`?

**Comment by abinashdash17** [comment]
I'm using `mount -o bind storage/external-1/arch arch`. Can it be the source of this error? I can confirm i've proper read,write and execute permisssions.

**Comment by abinashdash17** [comment]
As memorycard is formatted as fat32, there might be a problem in setting permission.
