### ISSUE TITLE
Please help Me with Dbus on Arh Linux

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#50]
Yesterdays night have been one of my best nights of my life. Why? Because I have successfully installed ArchLinux thanks to yours wonderful script. And I have been able to run Seamonkey including E-mail. Would you tell Me The secret, how did you managed so reliable shared memory support, that even complex native so libraries which are The part of Seamonkey can work? in 2017 Seamonkey did not work in Arch Linux like today.
I could only use Seamonkey browser but E-mail client could not be started. There was error related to shared memory support.
But now, there was really A miracle.
Or Newest stable Seamonkey contain routines which do not use shared memory when it is not presented?

But I Am fighting with Dbus. And it is non easy fight mission.
To be able to use Orca, mate desktop environment and Seamonkey, I always must run
dbus-launch app name &

But this is not A solution. Some mate parts gives errors related to Dbus.
Do you think, that there would be some work around, which would setup Dbus by The way that it would not cause errors?

What is currently possible?
Switch between windows even with Marco thanks to work around related to /proc/stat

It is even possible to use Seamonkey includingHTML compositor and E-mail client.
This is my biggest joy.
Distro can be safely and reliably upgraded and even terminated.
Exit correctly closes all sub processes, so user do not have to manually terminate xinit or XVFB.
Termination do not corrupt installed file system so distro work perfectly.
After this analysis, I have 100 % decided to use only Arch Linux and yours script.
It really seems to Me, that shared memory is solved The by The best eay.

I have even solved issue with Speech-dispatcher and sound output.
I Am using Espeakng package instead of Espeak.
And I have setup Pulseaudio for Termux to use Unix sockets thanks to professional advice from MR Pliush.
As A result, I have very usable Linux distribution.

I will also install Xorg dummi video driver instead to XVFB I will save several MB of RAm and some CPU cycles.
So Mr Rausty and others contributions. Very well done.
Proot programmers and Android developers have saved my dream. They have repaired Pokedata and Proot developers are also doing their best to make their app as stable and as fast as possible.

If there is some technique which would make my life with Dbus more efficient and reliable, please let Me know, Sure, I Am ready to test with you and reinstall whole distro, if something will crash.
Thank you again.

**Comment by kcubeterm** [comment]
> I have even solved issue with Speech-dispatcher and sound output.

@JanuszChmiel Can you help me or share script how did you setup.

**Comment by JanuszChmiel** [comment]
There is significant proggress related to DBUS on Arch Linux.
You must always run mate-session by typing
dbus-run-session mate-session &
and before zou will run Mate for The first time, run orca before
mate/session bz tzping
dbus-run-session orca &

dbus-run-session command run perfectlz. It is much more better to use
dbus-run-session than dbus-launch

You can setup ArchLinux to be usable with Orca and GTK apps only when you
will use VNC Android client app. And by using xinit and special xorg.conf
file.
Tigervnc and other similar apps have some issues with XXKB X11 protocol
support so Orca will never run thanks to it.

But keep in mind, that you will always get some limitations. Android lack
support for shared memory. Some kind man have recoded Seamonkey for ARM64
for Arch Linux so it do not call shared memory. Somebody have been so
proffesional that .so libraries, which calls shared memory have been
reprogrammed.
Userland contain special .so libraryes which are triing to emulate shared
memory support. But it has disadvantages.
Some apps crash. I have found out, that The best approach is really to use
Termux, Proot and ArchLinux script from MR Rausty.
MR Rausty is doing his best and his scripts are containing special code to
configure The system.

To be able to use The sound, you must use Pulseaudio for Termux it is The
most fastest approach for Android. And I Am using Unix sockets. The good
would be to compile Mbrola for ARM64 directly on installed archLinux.
Because Espeak and speech-dispatcher produces some delay.
I have even compiled Gradio and Orca and other apps from running Archlinux
for Termux.

You can use Seamonkey, Firefox, and even Thunderbird. Mate-session uses
ALT+F1 and ALT+f2 keys. Scan codes are different from Android, so you will
have to run mate-control-center first. Proot is so stable, that it is even
possible to run ArchLinux in background for 12 hours or longer.
BUt 4 GB RAm and more is required to be able to use The system effiiently.

**Comment by JanuszChmiel** [comment]
Setup yours ArchLinux environment by using The following commands.

addauser some username
This will add user name with no need to enter password. This user account
will not be The administration root password.
When you will run startarch script it will run ArchLinux with Root account.

But it is necessary to run X11 session and Orca and other related modules
always as non root user. I have got The Dbus in to unresovable scenario,
when I have exexuted it as root.

So as root user install The following packages.

pulseaudio-alsa
Module which will communicate with Pulseaudio sound server which run from
Termux by using Unix sockets or by using TCP/IP sockets

xf86-video-dummy 
If you would want to use screen reader and X11 apps without graphical
output.

xorg-server-xvfb
If you are partially sighted and you would rather want a VIdeo output.
x11-vnc
Special module which will allow you to use VNC protocol to communicate with
running X11 app. YOu would need A functioning VNC client Android app.
FInding compatible with screen reader and free was my most difficult task.
I have found The following app. It seems to Me, that it is The best free VNC
client and fully accessible with Android accessibility suite and with other
screen readers for Android, which is not common.

https://play.google.com/store/apps/details?id=com.iiordanov.freebVNC&hl=en

espeak-ng
Necessary to install, only this Espeak module work with Speech-dispatcher. 

xorg-xinit 
Contain xinit script to initialize Xorg correctly.

Add The following line to The /etc/X11/Xwrapper.config

allowed_users = anybody
This will allow you to run Xorg server correctly. In other case, you would
get error that only console users are allowed to run.

To enable sound support for ArchLinux, you have two options.
Use build in Pulseaudio for Termux as a Pulseaudio player. The reactivity
depend on Android kernel drivers and on Android kernel setup and development
quality.
The sad situation is, that Android 8 and newer is having some issues with
sound drivers even when you will use official Android apps to play sounds.
The problem is that speech synthesis is very specific activity related to
sound drivers.
Synthesizer play short chunks of audio samples and there are various delays
before The sound playback stop and start. By other words. You can listen
long line, you can type fast on keyboard and listen every characters and The
time delay before The individual spoken characters depend on The typing
speed. It is not continuos sound playback as when you will play some
continuos music MP3 file.
Solving this complex problem related to some initialisation time for Espeak
is complex and very difficult task for absolvents of informatic studies.
Because it is so complex to overcome this problem, that it is very unlikely
that somebody would try to fix it for free.

So for now, you will get some delay before keypress and sound output from
Espeak. I do not know if is it cause by Proot, which must use many backtrace
routines and many code to allow us to run Linux on Android OS. Or if The
problem is caused by some Kernel development algorithms which gives lower
priority to some background Android services to operate sound. 
To test how The delay is long, you must setup Termux first.
So.
From yours running Termux shell

apt install pulseaudio sox
cd ..
cd usr
cd etc
apt install nano
nano profile
Add The following two lines after last line file of The profile file

pulseaudio --start --exit-idle-time=-1
pactl load-module module-native-protocol-unix
socket=/data/data/com.termux/files/home/arch/tmp/pulse.sock auth-anonymous=1

Run arch Linux by typing
startarch
edit yours /etc/profile
you must cd arch
and type nano /etc/profile
and again. Add this line to The profile file. It must be  after last line of
this file.

export PULSE_SERVER=unix:/tmp/pulse.sock

Type exit. Restart Termux correctly, So PUlseaudio will be initialized. So
exit also termux by typing exit
And then run Termux

startarch
And type spd-say "I AM testing if Espeak speak by using Pulseaudio in
Termux."

You will notice some delay before spd-say will produce speech.
Unfortunately, this delay will persists across The all Espeak activities.
Mbrola could help, but you would had to compile it yourself on running Arch
Linux on Termux. You would had to also compilembrolaespeak driver. So The
task would not be trivial. I do not guarantee, that Mbrola will produce
speech. If it uses some memory shared sys calls, it will fail.
The similar issue exist for Festival. How to make it work with Arch Linux on
Termux.

The last hope would be if somebody kind would prepare Espeak and
speech-dispatcher directly for Termux. So ArchLinux would communicate with
Speech-dispatcher and Espeak by using sockets. But I do not know, if it
would be possible to redirect sockets communication from Arch Linux folder
tree to Termux folder tree and only for The communication with
speech-dispatcher.
According to my opinion, sound and initialisation delay would really stop
only, if some C programmer would have some time to recode Speech-dispatcher
and Espeak directly for Termux.
So The code of those modules would not had to be performed by using Proot.
But I have disappointed MR Grimmrel. I have forgottenon his complex work. He
has prepared functioning Speech-dispatcher for Termux. But I have
intensively tested Debian script in Termux and he has removed compiled
binary and package from his server and I do not think, that he would want to
prepare The new one, even I have kindly excused to him.

To have X11 apps working with no issues 
Add The following line to /etc/profile on arch Linux folder tree
so always ensure that you will use arch folder as yours root folder.

export DISPLAY=:0
The best approach for visually impaired user with no sight at all is to use
dummi display driver. It will reduce The amount of error messages related to
graphic output problems in Termux console screen. You will save some CPu
time and memory allocations should be smaller.

You will have to copy specially prepared xorg.conf file which will allow you
to run Xorg without real display driver.
https://gist.github.com/divinity76/ce210b5dbcd9ea7d0585ac403caef577#file-x11
-dummy-configuration-txt
you can use 
wget
https://gist.github.com/divinity76/ce210b5dbcd9ea7d0585ac403caef577#file-x11
-dummy-configuration-txt
Copy this file to /etc/X11/xorg.conf
Install xterm
run dbus-run-session xinit &
install Orca screen reader and some apps for testing.
pacman -S orca 
pacman -S ratpoison
It is light eweight non graphically oriented window manager.
Sure. you can install mate, because it is fully accessible. It uses Marco by
default. I do not recommend you to combine Mate included apps with other
window manager than Marco. You will very probably lost focus in some mate
apps GUIS while pressing TAB or SHIFT+TAB.
As a last advice.
Always run mate by typing
dbus-run-session mate-session &

To control X11 sessions run VNC app which I have rerecommended to you.
Tigervnc and other VNC servers for ArchLinux do not work with Orca. Orca has
issues with XKB protocol extension.
 So it can not start. XVFB uses graphical support, which causes many various
error messages because 3D hardware acceleration is not presented.
