### ISSUE TITLE
TemuxArch WARNING: Generated script signal 1 near or at line number 615 by 'trap'!

### ISSUE THREAD

**Issue by SkF0023** [SDRausty/termux-archlinux#56]
Hello, I am new to termux and was trying to get termux-arch working. I am on a chrome book (dell 5190 2 in 1) and following method 2 from [here](https://termuxarch.github.io/docsTermuxArch/install), and I keep getting the warning "TemuxArch WARNING: Generated script signal 1 near or at line number 615 by 'trap'!". Then when I run ./arch/startarch I get the error, 
proot error: 'usr/bin/env' not found (root = /data/data/com.termux/files/home/arch, cwd = /data/data/com.termux/files/home, $PATH=(null))
fatal error: see 'proot --help'.

I saw that maybe I should do, "setupTermuxArch.bash refresh" but that fails with "The root directory structure is incorrect; Cannot continue setupTermuxArch.bash refresh!"

I am not really sure what I am doing wrong.

**Comment by SkF0023** [comment]
Output of setupTermuxArch.sh sysinfo

Setting mode to sysinfo.

 🕛 > 🕛 TermuxArch 2.0.12 shall create a system information file.  Ensure background data is not restricted.  Run bash setupTermuxArch.bash help for additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Found download tool `curl`: Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    501      0 --:--:-- --:--:-- --:--:--   503
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30086  100 30086    0     0  99622      0 --:--:-- --:--:-- --:--:-- 99622

 🕛 > 🕐 TermuxArch download: OK

 🕛 > 🕜 TermuxArch 2.0.12 integrity: OK

Generating TermuxArch system information; Please wait…

Begin TermuxArch 2.0.12 system information.

dpkg --print-architecture result:

i686

uname -a results:

Linux localhost 4.4.176-16038-g1367a8f4b427 #1 SMP PREEMPT Wed May 15 13:54:54 PDT 2019 i686 Android

BASH_VERSINFO[0] = 5
BASH_VERSINFO[1] = 0
BASH_VERSINFO[2] = 16
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = i686-pc-linux-android

cat /proc/cpuinfo results:

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 92
model name      : Intel(R) Celeron(R) CPU N3350 @ 1.10GHz
stepping        : 9
microcode       : 0x2c
cpu MHz         : 1000.000
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 21
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch intel_pt kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdseed smap clflushopt sha_ni xsaveopt xsavec xgetbv1 dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 2188.78
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 92
model name      : Intel(R) Celeron(R) CPU N3350 @ 1.10GHz
stepping        : 9
microcode       : 0x2c
cpu MHz         : 1000.000
cache size      : 1024 KB
physical id     : 0
siblings        : 2
core id         : 2
cpu cores       : 2
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 21
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch intel_pt kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdseed smap clflushopt sha_ni xsaveopt xsavec xgetbv1 dtherm ida arat pln pts
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 2188.78
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:


Download directory information results:

/sdcard/Download exists
/storage/emulated/0/Download exists
~/downloads not found
/data/data/com.termux/files/home/storage/downloads exists

Device information results:

/dev/ashmem exists
/dev/ashmem is readable
/dev/shm does not exist
/dev/shm is not readable
/proc/stat exits
/proc/stat is readable

getprop results:

[getprop gsm.sim.operator.iso-country]: []
[getprop net.bt.name]: [Android]
[getprop net.dns1]: [192.168.1.1]
[getprop net.dns2]: []
[getprop net.dns3]: []
[getprop net.dns4]: []
[getprop persist.sys.locale]: [en-US]
[getprop ro.build.target_country]: []
[getprop ro.build.version.release]: [7.1.1]
[getprop ro.build.version.preview_sdk]: [0]
[getprop ro.build.version.sdk]: [25]
[getprop ro.com.google.clientidbase]: []
[getprop ro.com.google.clientidbase.am]: []
[getprop ro.com.google.clientidbase.ms]: []
[getprop ro.product.device]: [coral_cheets]
[getprop ro.product.cpu.abi]: [x86]
[getprop ro.product.first_api_level]: [25]
[getprop ro.product.locale]: [en-US]
[getprop ro.product.manufacturer]: [google]
[getprop ro.product.model]: [coral]

Disk report 20020176 on /data Tue Apr  7 16:08:33 EDT 2020

df /data/data/com.termux/files/home/arch results:

Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/mmcblk1p1  25639140 4293508  20020168  18% /cache

df results:

Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/loop1        435840  435840         0 100% /
/dev/loop4         47872   47872         0 100% /vendor
tmpfs            1959688     164   1959524   1% /dev
tmpfs            1959688       0   1959688   0% /dev/socket
tmpfs            1959688       0   1959688   0% /dev/usb-ffs/adb
tmpfs            1959688       0   1959688   0% /var/run/arc
tmpfs            1959688       0   1959688   0% /var/run/arc/sdcard
/dev/fuse       25639140 4293508  20020168  18% /var/run/arc/sdcard/default/emulated
/dev/fuse       25639140 4293508  20020168  18% /var/run/arc/sdcard/read/emulated
/dev/fuse       25639140 4293508  20020168  18% /var/run/arc/sdcard/write/emulated
tmpfs            1959688       0   1959688   0% /var/run/arc/obb
tmpfs            1959688       0   1959688   0% /var/run/arc/media
passthrough     25639140 4293508  20020168  18% /var/run/arc/media/MyFiles
passthrough      1959688       0   1959688   0% /var/run/arc/media/removable-write
passthrough     25639140 4293508  20020168  18% /var/run/arc/media/MyFiles-default
passthrough      1959688       0   1959688   0% /var/run/arc/media/removable-read
passthrough     25639140 4293508  20020168  18% /var/run/arc/media/MyFiles-read
passthrough      1959688       0   1959688   0% /var/run/arc/media/removable-default
passthrough      1959688       0   1959688   0% /var/run/arc/media/removable
passthrough     25639140 4293508  20020168  18% /var/run/arc/media/MyFiles-write
tmpfs            1959688       0   1959688   0% /sys/kernel/debug
run              1959688     788   1958900   1% /sys/kernel/debug/tracing
tmpfs            1959688      12   1959676   1% /oem/etc
tmpfs            1959688       0   1959688   0% /mnt
tmpfs            1959688       0   1959688   0% /dummy

du -hs /data/data/com.termux/files/home/arch results:

640K    /data/data/com.termux/files/home/arch

ls -al /data/data/com.termux/files/home/arch results:

total 84
drwx------  8 u0_a53 u0_a53 4096 Apr  7 15:57 .
drwx------ 14 u0_a53 u0_a53 4096 Apr  7 16:08 ..
drwx------  2 u0_a53 u0_a53 4096 Apr  7 15:48 etc
-rw-------  1 u0_a53 u0_a53  220 Apr  7 15:48 md5sums.txt
drwx------  3 u0_a53 u0_a53 4096 Apr  7 15:48 root
drwx------  3 u0_a53 u0_a53 4096 Apr  7 15:48 run
-rwx------  1 u0_a53 u0_a53 6903 Apr  7 15:48 startarch
drwxrwxrwt  3 u0_a53 u0_a53 4096 Apr  7 16:08 tmp
drwx------  3 u0_a53 u0_a53 4096 Apr  7 15:48 usr
drwx------  3 u0_a53 u0_a53 4096 Apr  7 15:48 var

End `setupTermuxArchSysInfo1910.log` 2.0.12 system information.

Share this information along with your issue at https://github.com/sdrausty/TermuxArch/issues; include input and output.  This file is found in `/data/data/com.termux/files/home/setupTermuxArchSysInfo1910.log`.  If you think screenshots will help in a quicker resolution, include them in the post as well.

This information may be quite important when planning issue(s) at https://github.com/sdrausty/TermuxArch/issues with the hope of improving `setupTermuxArch.bash`;  Include input and output, along with screenshot(s) relavent to X, and similar.

setupTermuxArch.sh sysinfo 2.0.12: DONE 🏁

$ bash TermuxArch/setupTermuxArch.sh sysinfo > file.out
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    874      0 --:--:-- --:--:-- --:--:--   879
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30086  100 30086    0     0   466k      0 --:--:-- --:--:-- --:--:--  466k

**Comment by TylesRose** [comment]
Try this commands in Termux:
`pkg update -y`
`pkg upgrade`
`pkg install bsdtar -y`

**Comment by SkF0023** [comment]
I tried that, but still got the warning "TermuxArch WARNING:  Generated script signal 1 near or at line number 109 by `sed '2q;d' md5sums.txt > "$IFILE".md5`!" when running bash setupTermuxArch.bash. 
Then when I run ./startarch I get the error 
"proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/arch, cwd = /data/data/com.termux/files/home/arch, $PATH=(null))
fatal error: see `proot --help`."

**Comment by SDRausty** [comment]
@SkF0023 there have been quite [a few changes](https://github.com/TermuxArch/TermuxArch/commits/master) since you first posted this issue.  Is this WARNING resolved on your device?

**Comment by SkF0023** [comment]
I don't actually have that device anymore. Sorry about that, I thought I had already resolved it.
