### ISSUE TITLE
/proc not mounted - LibreOffice is unlikely to work well if at all         

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#58]
Dear Mr Rausty,
Yours script can install fully functioning Arch Linux to various Android devices. You have done yours best to overcome Android 8 limitation. /Proc folder can not be mounted.
Unfortunately, Libreoffie want to directly access this folder.
So when I want to run it from The mate by using Libreoffice link I AM getting The following error.

/proc not mounted - LibreOffice is unlikely to work well if at all       
 Do you think, that there is some possibility how to managing /proc at The background from Termux. So if some app which run by using Proot request for /proc that this request could be damaged by some daemon app which run in Termux like compiled C or C++ binary?
Or unfortunately, it is impossible o Android 8 and non rooted ANdroid OS? Because Libreoffice really want to access not only formal content but The real content of /proc folder?

Thank you very much for yours explanation.
And dbus-run-session app name &
Have solved manz Dbus errors and szstem is now very stable.

**Comment by SDRausty** [comment]
Retesting the install feature is requested as, ["Issues with Libreoffice #252"](https://github.com/SDRausty/TermuxArch/issues/252) was opened.  Should device space be an issue with your device smartphone, wearable, smartwatch and more, please run this command:
```
bash setupTermuxArch re
```
This will refresh the installation to the newest version for development, testing and the ux (user experience) should space on device NOT be an issue, please use the alternate directory install feature; `setupTermuxArch h` has more information about the alt directory install  feature; cocurrent Linux versions on smartphone and more with the `setupTermuxArch i` option are possible.  Please see option `setupTermuxArch h` for more information.

**Comment by JanuszChmiel** [comment]
Libreoofice work smoothly now thanks to update of one expert which have been
applied several month ago.
Now, I can run Libreoffice with no issues at all.
Thank you for yours repair. User do not have to care about it. Simply
install pacman -S libreoffice, finish installation process and Libreoffice
suite work like A charm.

**Comment by SDRausty** [comment]
> Libreoffice work smoothly now 

@JanuszChmiel thank you very much for confirming Libreoffice works on smartphone!

**Comment by JanuszChmiel** [comment]
Yes, work ammazingly. And even spell checking feature with Orca work without
problems.
For all visually impaired future users. Espeak-ng can not be used on higher
speech speed than 72. Higher speed produces big error, that when arrow keys
are being used for browsing inside editable fields, that Espeak-ng
synthesizer jump one character and speak The second one.
This complex issue can be solved only by very experienced C programmer, who
knows Speech-dispatcher source code and Espeak-ng very well.
To avoid those issues, users must use older espeak package, where those
problems do not exists at all.
Or use espeak-ng on The speed 72 with Orca no faster.
