### ISSUE TITLE
Chromium, Firefox, Libreoffice, Epiphany, localectl, timedatectl...

### ISSUE THREAD

**Issue by pantumaca** [SDRausty/termux-archlinux#6]
I am having problems with:
 
- Chromium -> SUID is present but not configured. Check /chromium.conf (it seems ok)
- Firefox -> Black screen with any web
- Epiphany -> White screen with any web
- Libreoffice -> prod is not mounted
- Localectl and timedatectl -> command not found

Anybody can work with those app/commands?

Thanks!

EDIT: Better i post this here -> https://github.com/sdrausty/TermuxArch/issues

**Comment by sdrausty** [comment]
You are welcome:

#### Here are some links where repeating the topics mentioned may be worth the effort and time.
Email : termux+subscribe@groups.io
Github : https://github.com/termux/
Gitter : https://gitter.im/termux/termux
Termux Community : https://plus.google.com/communities/101692629528551299417
Try Arch Linux https://github.com/archlinuxarm too. 
https://github.com/ArchStrike/ArchStrike 
https://wiki.archlinux.org/index.php/IRC_channel

 When you find answers, share them here for us all.  Topic closed as this is beyond BASH setup script.

**Comment by nxd84** [comment]
You can fix firefox black screen by seeing the video, link given bellow.

[](url)https://www.youtube.com/watch?v=ugKk1tz46mk

**Comment by SwapnilSoni1999** [comment]
not helpful at all

**Comment by LeapofAzzam** [comment]
I got Chromium working:
![Screenshot_2020-04-19-13-25-37-23_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/48548847/79681107-52b06b00-8241-11ea-8c08-de7916209ed7.png)

**Comment by SDRausty** [comment]
Retesting the install feature is requested as, ["Issues with Libreoffice #252"](https://github.com/SDRausty/TermuxArch/issues/252) was opened.  Should device space be an issue with your device smartphone, wearable, smartwatch and more, please run this command:
```
bash setupTermuxArch re
```
This will refresh the installation to the newest version for development, testing and the ux (user experience) should space on device NOT be an issue, please use the alternate directory install feature; `setupTermuxArch h` has more information about the alt directory install  feature; cocurrent Linux versions on smartphone and more with the `setupTermuxArch i` option are possible.  Please see option `setupTermuxArch h` for more information.
