### ISSUE TITLE
Libreoffice do not work because /proc can not be accessed

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#60]
Dear MR Rasuty and others,
On Android 8 and newer, /proc folder can not be accessed. Work around which is being used by  yours script can help to run Marco window managgger and many other apps, which need to access /proc folder. But unfortunately Libreoffice uses other access to /proc. do you think, that there is some way how to make Libreoffice work? I Am presenting yours script on various places and forums. It is really The best available solution to run Linux. Termux and its Proot variant is so robust and stable, that it is really possible to run Linux for several days including graphical desktop without instability. If there is no other work around, how complex would be to reprogram Libreoffice so it will access its sub modules in Ram by not using /proc folder?
Thank you very much for yours thinkink and sure, I Am ready to test.
VLC media player and many other QT apps are even fully accessible with Orca. I have even built Lazarus latest version successfully for AARch64 Bit edition. I Am finding very big potential while using yours script. I Am convinced, thaat if there is any solution, you will know about it MR Rausty.

**Comment by SDRausty** [comment]
> /proc can not be accessed 

Is this still current @JanuszChmiel?

**Comment by petkar** [comment]
[Here's](https://github.com/EXALAB/AnLinux-App/issues/24#issuecomment-543143007) a workaround to get libreoffice working.
```
You can edit file /usr/lib/libreoffice/program/oosplash with any HEX editor (bless for example; use `pacman -S bless` and launch it from a graphical environment). Use the search option to find the text "/proc/version" (LibreOffice checks this file) and change it to for example "/prod/version". NOTE: make sure you run `mkdir /prod` and `touch /prod/version` (to create fake empty "/prod/version" file in the filesystem). After this Office starts and works well (source code says /proc is very important but I can't find any issue, maybe because /proc partially accessible since it is "mounted" with proot to the guest system).
Not very fine method but now is the only one without root.
```

**Comment by JanuszChmiel** [comment]
Thank you very much for yours next useful tip.
I must buy some other Android hone on future with 6 GB of RAm and without
partially case file insensitive file system. To have faster big files load
on Linux.
Libreoffice get long load even on normal computers.

**Comment by SDRausty** [comment]
This pull https://github.com/TermuxArch/TermuxArch/pull/12 request contributed by @petkar resolves this issue:

> [tested it and Libreoffice starts up perfectly now with no additional tweaking required.](https://github.com/SDRausty/TermuxArch/issues/242)

**Comment by SDRausty** [comment]
Retesting the install feature is requested as, ["Issues with Libreoffice #252"](https://github.com/SDRausty/TermuxArch/issues/252) was opened.  Should device space be an issue with your device smartphone, wearable, smartwatch and more, please run this command:
```
bash setupTermuxArch re
```
This will refresh the installation to the newest version for development, testing and the ux (user experience) should space on device NOT be an issue, please use the alternate directory install feature; `setupTermuxArch h` has more information about the alt directory install  feature; cocurrent Linux versions on smartphone and more with the `setupTermuxArch i` option are possible.  Please see option `setupTermuxArch h` for more information.
