### ISSUE TITLE
shared memory question

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#61]
I have found out, that startarch script contain special command to emulate sharing memory by creating virtual folder /dev/shm. Does it mean, that in this case, build in C library, which is The part of ArchLinux can fully support shared memory? Or is it still necessary to load .so special library to support this feature?

**Comment by SDRausty** [comment]
> Some developers declare that if shared memory work as it should, that apps should run faster.

Speed can be tested with this [`stdoutbench.sh` ](https://github.com/TermuxArch/scripts.TermuxArch/blob/master/frags/stdoutbench.sh) script.

**Comment by SDRausty** [comment]
> Some developers declare that if shared memory works as it should apps should run faster.

Speed can be tested with this [`stdoutbench.sh` ](https://github.com/TermuxArch/scripts.TermuxArch/blob/master/frags/stdoutbench.sh) script.
