### ISSUE TITLE
Please try to convince aarch64 repo managers to prepare shortwave packages.

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#62]
Dear kind and professional MR Rausty,
Do you think, that you could try to convince Aarch64 repositoryes managers to add Shortwave radio player and recorder to one of available repositoryes, which yours perfect installation script configures?

I have spent many many hours to build Shortwave myself. But Libhandy specific version is needed and Mr Haecker, C programmer who work for GNome foundation has given Me a link for Libhandy version for X86 or X64 architecture. So I do not know, if I should build this library from source. Repo available version is incompatible and Shortwave build fail. Gradio can be build perfectly with no issues at all.
https://gitlab.gnome.org/haarek/Shortwave

Any help to build is very welcomed.

**Comment by SDRausty** [comment]
> Any help to build is very welcomed.

The recently added command `makeyay` enables `yay` which in turn enables building Arch Linux packages from the `aur` repository.  Can you see if any of these projects are to your liking @JanuszChmiel?  Many of these packages should build easily and quickly in your smartphone.

**Comment by JanuszChmiel** [comment]
Oh dear kiND MR Rausty,
Previously I have used official approach which The author of Shortwave has
introduced. BUt resulting binary compiled code has crashed thanks to some UI
creation library error.
Aur rpo contain many packages which are currently not The aprt of The
predefined Arrch64 repo.
I will really install archlinux back to my phone to see new package building
possibilityes.
Gradio has stopped to work for Me. Because radio-browser.info WEB page has
change and build in Vala routines could not cooperate with this online radio
station searching service. So I can not use Gradio no more. Shortwave had
unsoft accessibility. Gradio have been much more accessible. But I can not
become Vala coder so I will try to use latest Shortwave to see The result.

**Comment by SDRausty** [comment]
Can you try the newly working [`makeyay`](https://github.com/SDRausty/termux-archlinux/blob/master/archlinuxconfig.bash#L623&&#L643) command that builds `yay` to see if it builds the packages you are seeking?

Use the `makeyay` command first.  This will make the `yay` command for you, so that `yay` can be used in Arch Linux in a  smartphone:
```
[user14:17~]$ yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 there is nothing to do
[user14:30~]$ yay -V
yay v10.0.4 - libalpm v12.0.2
```

**Comment by SDRausty** [comment]
Can you try the newly working [`makeyay`](https://github.com/SDRausty/termux-archlinux/blob/master/archlinuxconfig.bash#L623&&#L643) command which builds `yay` to see if it builds the packages you are seeking?

Use the `makeyay` command first.  This will make the `yay` command for you, so that `yay` can be used in Arch Linux in a  smartphone:
```
[user16:19~]$ yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 there is nothing to do
[user16:20~]$ yay -V
yay v10.0.4 - libalpm v12.0.2
[user16:21~]$ yay -Ss shortwave
aur/slowrx-git r128.1760187-1 (+3 0.00)
    An SSTV decoder that aims for intuitive simplicity and lack of features not needed by a shortwave listener (SWL).
aur/shortwave-git 1.1.1.r45.g4ab88a6-1 (+7 0.15)
    Find and listen to internet radio stations
aur/shortwave 1:1.1.1-1 (+20 2.94)
    Find and listen to internet radio stations.
```

**Comment by SDRausty** [comment]
> will try to use latest shortwave to see the result.

```
[user09:35~]$ yay shortwave|grep Installed
3 aur/slowrx-git r128.1760187-1 (+3 0.00) (Installed)
```
The `slowrx-git` package compiled quickly @JanuszChmiel; To make the command `yay` you can use `makeyay`.

**Comment by JanuszChmiel** [comment]
Please, who of us would have some time and would try to help Me to install
and BuildShortwave by using Yay?
 
Unfortunately, my GIthub build by using yay -s shortwave
have no success to build.
There was error with libhandy library.
Gradio code is outdated and is incompatible with up to date
radio-browser.info domain.
Yay is perfect packager builder, but libhandy library is very strange
library.
If somebody had success to build some Shortwave release, and if Shortwve
really run without display error related to some Libhandy issue, please
give Me step by step instruction to build it.
 
Problem is not caused by Yay but it is some problem caused by The build
script related to Shortwave build routines.
Thank you very much for yours patience.
I love soft and slow romantic songs from 80S. And it is so fine feeling to
llisten those songs from Linux on Android device.
May be, that somebody would be even so big professwional, that Shortwave
could become official AArch64 compatible official AUR repository package.
But We must be patient to allow his app to be The part of ARU repo.

**Comment by SDRausty** [comment]
> who of us would have some time and would try to help me to install and build shortwave by using yay?

@JanuszChmiel what is the output of these commands on your smartphone?
```
$ getprop ro.product.cpu.abi
armeabi-v7a
$ getprop ro.build.version.release
9
```

> There was error with libhandy library.

```
[user09:54~]$ yay libhandy
5 aur/libhandy1-wip-git 0.85.0.r41.g75a5abd-1 (+0 0.00)                           
Library full of GTK+ widgets for mobile phones
4 aur/libhandy-glade-catalog-disabled-git 0.91.0.r1.ge3fb740-1 (+1 0.09)          
Library full of GTK+ widgets for mobile phones                            
3 aur/libhandy-git 0.91.0.r1.ge3fb740-1 (+3 0.00)
Library full of GTK+ widgets for mobile phones                            
2 aur/libhandy1 0.91.0-1 (+6 3.67)                                                
Library full of GTK+ widgets for mobile phones (1.0, can be installed alongside 0.0)
1 community/libhandy 0.0.13-2 (413.0 KiB 2.0 MiB)                                 
Library full of GTK+ widgets for mobile phones                            
==> Packages to install (eg: 1 2 3, 1-3 or ^4)                                
==> 1
⋮
[user10:00~]$ pacman -Ql libhandy
```
Installed like a charm by the looks of it.  The command `pacman -Ql libhandy` produced a lot of output.  I will [take a look again](https://github.com/SDRausty/termux-archlinux/issues/62#issuecomment-678808866_), and see how short wave packages build again; Have you had any success with these builds?
```
[user10:02~]$ yay shortwave                                                   
3 aur/slowrx-git r128.1760187-1 (+3 0.00)
An SSTV decoder that aims for intuitive simplicity and lack of features not needed by a shortwave listener (SWL).
2 aur/shortwave-git 1.1.1.r45.g4ab88a6-1 (+7 0.11)                                
Find and listen to internet radio stations
1 aur/shortwave 1:1.1.1-5 (+26 7.33)                                              
Find and listen to internet radio stations.
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==>
```
And what about this? How did these builds go for you? Did you have any success?
```
[user10:00~]$ yay gradio
2 aur/gradio-git 7.1-1 (+8 0.00) (Out-of-date: 2018-11-28)                        
A GTK3 app for finding and listening to internet radio stations
1 aur/gradio 7.3-1 (+55 0.03)                                                     
A GTK3 app for finding and listening to internet radio stations
==> Packages to install (eg: 1 2 3, 1-3 or ^4)                                ==>
```

**Comment by SDRausty** [comment]
```
Compilation succeeded - 25 warning(s)
[62/63] Installing files.
Installing data/de.haeckerfelix.gradio.desktop to /home/user/.cache/yay/gradio/pkg/gradio/usr/share/applications
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Error getting authority: Error initializing authority: Could not connect: No such file or directory
FAILED: meson-install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in package().
    Aborting...
error making: gradio
```
You might be surprised to know that this output is good news.  This is the key line `Compilation succeeded - 25 warning(s)` of the good news news. Let us see what we can do to turn this good news into great news.

**Comment by JanuszChmiel** [comment]
Thank you very much. If I will not have The chance to build Shortwve, I will
accept sad reality and I will use Seamonkey to listen radio by using
http://www.radio-browser.info/gui/#!/
$ getprop ro.product.cpu.abi

 arm64-v8a 
 
Gradio will never work thanks to new 
radio-browser.info
WEB site. Somebody would had to recode Vala Gradio source to support this
WEB site. Gradio have been perfect player and have been fully compatibleš
with Orca.
Now I must build Shortwave.

**Comment by SDRausty** [comment]
```
[user10:25~]$ cd .cache/yay/gradio/
[user10:32gradio]$ nano PKGBUILD
```
Let us cahange line `arch=('i686' 'x86_64')` to `arch=('i686' 'x86_64')` so it does not tell us we are using the wrong architecture anymore.  Also change:
```
package() {
        cd "${srcdir}/${_pkgname}-${pkgver}"
  DESTDIR="${pkgdir}" ninja -C builddir install
}
```
Add sudo before the command `ninja`:

```
package() {
        cd "${srcdir}/${_pkgname}-${pkgver}"
  DESTDIR="${pkgdir}" sudo ninja -C builddir install
}
```
Now we get to use this `makepkg -irs --noconfirm` command and it worked:

```
==> Leaving fakeroot environment.                                             ==> Finished making: gradio 7.3-1 (Tue 08 Sep 2020 10:49:34 AM EDT)
==> Installing package gradio with pacman -U...                               loading packages...                                                           resolving dependencies...                                                     looking for conflicting packages...                                           
Packages (1) gradio-7.3-1                                                     
                                                                              :: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [####################] 100%(1/1) checking package integrity                   [####################] 100%
(1/1) loading package files                        [####################] 100%(1/1) checking for file conflicts                  [####################] 100%
:: Processing package changes...                                              (1/1) installing gradio                            [####################] 100%
Optional dependencies for gradio                                                  gst-libav: H.264 video streaming
[user10:49gradio]$ gradio
```
Did you manage to get it to successfully build?

**Comment by JanuszChmiel** [comment]
$ getprop ro.build.version.release

 8.0.0 
janusz@localhost root]$ yay libhandy

 5 aur/libhandy1-wip-git 0.85.0.r41.g75a5abd-1 (+0 0.00)

     Library full of GTK+ widgets for mobile phones

 4 aur/libhandy-glade-catalog-disabled-git 0.91.0.r1.ge3fb740-1 (+1 0.09)

     Library full of GTK+ widgets for mobile phones

 3 aur/libhandy-git 0.91.0.r1.ge3fb740-1 (+3 0.00)

     Library full of GTK+ widgets for mobile phones

 2 aur/libhandy1 0.91.0-1 (+6 3.67)

     Library full of GTK+ widgets for mobile phones (1.0, can be installed
alongs
 ide 0.0)

 1 community/libhandy 0.0.13-2 (425.6 KiB 2.1 MiB)

     Library full of GTK+ widgets for mobile phones

 ==> Packages to install (eg: 1 2 3, 1-3 or ^4)

**Comment by SDRausty** [comment]
This one `1 community/libhandy 0.0.13-2 (425.6 KiB 2.1 MiB)` is already packaged.  There is no need to build it.

**Comment by JanuszChmiel** [comment]
To build gradio successfully.
It is necessary to grab The original version from Github
And then from Gradio folder
run
meson --prefix=/usr build
 
ninja -C build
 
ninja -C build install

Sure, you must install meson.
But really. radio will very probably not work to search for startions.
In Jun, it have worked. 
I have even built Shortwave successfully without Yay.
 No compilation errors. But binary could not run. I have got The following
error 
 
shortwave:15278): Gtk-ERROR **: 19:38:17.848: failed to add UI: .:3:984
Invalid
  object type 'HdyColumn'
 
Some C expert would had to determine The cause of this bug.

**Comment by SDRausty** [comment]
> Gtk-ERROR **: 19:38:17.848: failed to add UI: .:3:984

This sounds more like a GUI configuration than a C one.

**Comment by SDRausty** [comment]
> To build gradio successfully.

To build gradio successfully change `arch=('i686' 'x86_64')` to `arch=('any')` and add `sudo` before `ninja` in `package()` in file `PKGBUILD`. Do not continue the build with `yay`; Instead use `makepkg -irs --noconfirm` to finish the build with install.

**Comment by SDRausty** [comment]
This issue is currently open at this [https://github.com/SDRausty/termux-archlinux/issues/62](https://github.com/SDRausty/termux-archlinux/issues/62) link.

**Comment by SDRausty** [comment]
> To build `gradio` successfully.

Have you managed to build `gradio` successfully?

**Comment by JanuszChmiel** [comment]
Dear MR Rausty
Yes, I have built Gradio successfully even by using yay script or by building it manuály by using meson. Unfortunately, its source code have not been updated and special WEB site, which MR Haecker has used has changed.
So Gradio do not search for stations at all. Because
Radio-browser.info
Has changed its content. Some Vala expert would had to try to update its source according to this WEB page update.
Because Gradio is very very accessible. 


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
I AM afraid, that Libhandy library may be call some graphic driver functions so it has caused some error related to column creation. May be, that Libhandy do not interact with X11 protocol, but it uses some special video driver calls. Or if this library is compatible only with vaylant not with X11.
And I Am running TIgervnc and Tigervnc is based on X11.

I will try to ask The author of Libhandy. It will depend on his patienc and good will to debate. Because our mission, running Linux distro on userspace mode is sometimes not very welcomed by some apps authors. Because They had to recode their complex C or C++ codes to support also ArchlInux on Termux.
I will try to ask him.
But first of all, I will try to build Shortwave again according to advice of one Rust programming language community member.
It will built to Binary form, but Libhandy will display error related to column creation after I will execute Shortwave compiled Binary.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
> Gradio do not search for stations at all

As far as I know this is because the feature was being vandalized.  Would you like to try to reproduce this feature here?

In order to do so, the data link to the stations and the old config file locations are requested.  Can you please create a PR in [docsTermuxArch/issues/SDRausty/termux-archlinux/62](https://github.com/TermuxArch/docsTermuxArch/pulls) with this information?  If not, please share in this issue.
