### ISSUE TITLE
cannot use byobu

### ISSUE THREAD

**Issue by 0xdhrv** [SDRausty/termux-archlinux#63]

**Comment by SDRausty** [comment]
@0xdhrv `tmux` works as expected as far as I can tell, but for some reason `byobu` generates `open terminal failed: not a terminal`.  Can you try working with variable `PROOTSTMNT` in function [`_PR00TSTRING_`](https://github.com/SDRausty/termux-archlinux/blob/master/knownconfigurations.bash#L70&&#L123)  in file `knownconfigurations.bash` to see if this can be fixed?

**Comment by SDRausty** [comment]
@0xdhrv `tmux` works as expected as far as I can tell, but for some reason `byobu` generates `open terminal failed: not a terminal`.  Can you try working with variable `PROOTSTMNT` which creates the proot init string  through function [`_PR00TSTRING_`](https://github.com/SDRausty/termux-archlinux/blob/master/knownconfigurations.bash#L70&&#L123) to see if this can be easily fixed?

**Comment by SDRausty** [comment]
@0xdhrv at present I am getting the same error with both of the programs mentioned. Have you tried to solve `open terminal failed: not a terminal` by looking up this error message?  If you have, did you make any progress?

**Comment by SDRausty** [comment]
@0xdhrv tmux and byubo now work correctly.  I stumbled upon an offending backslash \ in file [`knownconfigurations.bash`](https://github.com/SDRausty/termux-archlinux/blob/master/knownconfigurations.bash#L124) and removed it last night.  

This working code `TERM=\"$TERM\"`  looked like this `TERM=\"\$TERM\"` before the change.  Not much of a difference is there @0xdhrv?  Then I tested the new code and was very surprised to find `byobu` and `tmux` working as expected in Arch Linux in Termux PRoot!  Enjoy and share your progress 🍀
