### ISSUE TITLE
What about system user services support at login?

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#64]
I have finally tried to analyse ArchLinux wiki. And I Am thinkink. Is it necessary to add some services which will be automatically started after login? The positive aspect of system user approach is that it is official ArchLinux routine so it should be fully compatible with ArchLinux chroot. It is even possible to add services which will ge started globally no mater which user account have been used to add and start them.
So which services should be started in user mode when I AM using tigervnc, mate-desktop-environment and sound support by using TCP socket?
Sure, I know, that I can not run services which are based on ArchLinux kernel calls, hardware detection, etc.
My most curious service is dbus. Sure. I can use dbus-launch dbus-run-session etc, but I AM thinkink if it would not be better to start dbus as service as it should be.
Here is The article about it.

https://wiki.archlinux.org/index.php/Systemd/User
And sure. If some important services should be started, this command could be part of Arch Linux setup scripts.

I Am very sorry, that I AM so deeply thinkink. BUt I AM recognizing ArchLinux deepr and deeper. And thanks to MRS Rausty scripts, it is very likely that this distribution will be The most profesionally installed distribution by using Termux and Proot.

**Comment by SDRausty** [comment]
> The positive aspect of system user approach is that it is official ArchLinux routine so it should be fully compatible with ArchLinux chroot.
https://wiki.archlinux.org/index.php/Systemd/User

Interesting, how would you consider implementing this @JanuszChmiel?

**Comment by JanuszChmiel** [comment]
aI Am thinkink.
What would happen, if The /dev/shmget folder would not reside inside root
/dev folder. But if /shmget would reside inside /dev/shm/shmget
Or it would not help?

**Comment by SDRausty** [comment]
The command `csystemctl` modifies `systemctl`.  This is a brand new feature.  Can you try the system users again please @JanuszChmiel.  There have been changes in the insulation and configuration section. 

If the commands you are trying to run do not work, see if the final outcome still works as expected.  Please post the steps you took and their outcome.  If they do work as expected, let us know here by all means.

**Comment by SDRausty** [comment]
This command [`csystemctl.bash`](https://github.com/SDRausty/termux-archlinux/blob/master/archlinuxconfig.bash#L197) was developed from this contribution;  [Workaround to get systemctl commands working on TermuxArch #239](https://github.com/SDRausty/TermuxArch/issues/239) and should provide system user services support at login as requested.
