### ISSUE TITLE
 How does the postgresql package build in Arch Linux in a smartphone?

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#65]
I will try to build The following packages. Version numbers are important, I can not use different versions.

postgresql-11 postgresql-11-postgis-2.5 postgresql-11-pgrouting
Sure. I Am not lazy. I know about aur repo. But in some cases, simply changing The corresponding line inside pkgbuild script is not enough. I AM writing about The line which defines target architecture. So simply defining aarch64 is not guarantee that package will be build successfully. In such acases, I would need yours help.
Postgressql is complex C app and building it on phone with Android Termux and Proot is not fast task. Especially because my phone is using strange ANdroid kernel, which needs to use several Proot work arounds to support files operation.

If I will go to troubles with C source while building, I will ask for help here.

**Comment by SDRausty** [comment]
> postgresql-11 postgresql-11-postgis-2.5 postgresql-11-pgrouting

Use the `makeyay` command first.  This will make the `yay` command so you that it can be used in Arch Linux:
```
[user13:56~]$ yay postgresql
212 aur/postgresql-libs-git 49068.d9a4cce29d-3 (+0 0.00)
    Libraries for use with PostgreSQL
.
.
.
1 extra/libgda-postgres 5.2.9-4 (143.0 KiB 1.5 MiB)
    libgda provider for PostgreSQL
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
```
212 of these packages are available.  I have not got around to building and testing whether they build as expected, they should. Please share your progress here @JanuszChmiel;  Enjoy!

**Comment by SDRausty** [comment]
> Postgressql is complex C app and building it on phone with Android Termux and Proot is not fast task. 

```
$ yay postgresql|grep Installed
40 aur/pgrouting 3.1.0-1 (+8 0.00) (Installed)
12 community/postgis 3.0.2-1 (2.6 MiB 31.6 MiB) (Installed)
7 extra/postgresql-libs 12.4-1 (1.1 MiB 6.3 MiB) (Installed)
5 extra/postgresql 12.4-1 (15.1 MiB 50.1 MiB) (Installed)
```
The `postgresql` packages compiled quickly @JanuszChmiel; To make the command `yay` you can use `makeyay`.
