### ISSUE TITLE
cant makepkg -si yay

### ISSUE THREAD

**Issue by pagkly** [SDRausty/termux-archlinux#68]
I got this error when `makepkg -si` for yay
>fakeroot, while creating message channels: Function not implemented
>This may be due to a lack of SYSV IPC support
>fakeroot: error while starting the 'faked' daemon

**Comment by SDRausty** [comment]
@pagkly try command `makeyay` from a user account.  This command goes through all the build steps automatically.  There are a couple of steps you need to do before `yay` builds.  The command [`makeyay`](https://github.com/SDRausty/termux-archlinux/blob/master/archlinuxconfig.bash#L626&#L646) does these for you.

**Comment by SDRausty** [comment]
This information is added to the [`makeyay`](https://github.com/SDRausty/termux-archlinux/blob/master/archlinuxconfig.bash#L626&#L646) command with this commit https://github.com/SDRausty/termux-archlinux/commit/cece860e3e1fd815fb3e1d908efecc151792e675:
```
When this message:                                                            
libtool: warning: remember to run 'libtool --finish /usr/lib/libfakeroot'
When this message is displayed on the screen 'makeyay' will deal with it a little bit later in the build proccess, and there will be a short pause when this message is displayed:
"Libraries have been installed in:"
A difficult part of any build process can be choosing the correct answers.  Here are the correct answers:                                                   
:: fakeroot-tcp and fakeroot are in conflict. Remove fakeroot? [y/N] y
Tap the 'y' key first, then enter.  For the first question, the 'y' key must be tapped first, then enter.  Yes will be chosen when enter is tapped in all of the questions after the first question:
:: Proceed with installation? [Y/n]
Tap enter x4 as this build proccess continues.  If everything goes well, you will see these messages:
Libraries have been installed in:
makefakeroottcp  2.0.476: DONE 🏁
and then this will go on to make 'yay' which is much simpler.  It is simply tapping enter which chooses the yes answer.
```
