### ISSUE TITLE
setuptermuxarch script causes error

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#69]
When I have executed Archlinux setup script, I AM getting The following error.

$ ./setupTermuxArch.bash                                                        
 ./setupTermuxArch.bash: line 646: SDATE: command not found                      
                                                                                 
  TermuxArch WARNING:  Generated script signal 201 near or at line number 646 by 
 'STIME="$(SDATE)"'!                                                             
                                                                                 
 setupTermuxArch.bash  2.0.522: [Exit Signal 201] DONE                          
                                                                                 
 Should I rename date binary to sdate inside bin directory of Termux? Or could you look at The problem please, I can not install.

**Comment by SDRausty** [comment]
Thank you for opening this issue @JanuszChmiel.  The diagnostic information was very helpful in resolving it quickly.  I have managed to find this error and correct it.  The solution has already been committed to GitHub, and I will let you know when it has migrated to this repository in this issue.

If you are interested in discussing these types of errors that do at times arise in these project, fortunately to be found and usually quickly corrected, sometimes not, @xd003 are discussing an error which magically appeared the night before, then apparently disappeared by itself at this https://github.com/TermuxArch/TermuxArch/issues/24 issue.

To continue without having to wait for the update in this repository,  you can simply run the script `setupTermuxArch` in a directory that does not have the accompanying files, and it will install without this issue, i.e:
` bash ~/storage/downloads/setupTermuxArch`

**Comment by SDRausty** [comment]
> `STIME="$(SDATE)"`

should read

`STIME="$SDATE"`

Please note the slight change it has caused script to fail.

**Comment by JanuszChmiel** [comment]
Thank you very much dear MR Rausty. i have started The script from
/storage/downloads and it run perfectly.
I will test shared memory and The special command to install packages. BUt I
AM afraid, that even this new command will be helpless to force Shortwave
from crashing thanks to Libhandy library.
But I will test it. Since I love Internet radio players very much and my
favourite song from 80S.

**Comment by SDRausty** [comment]
> test shared memory

@JanuszChmiel can you share how you do this? And also which programs do you use to listen to music from the 80s?

**Comment by SDRausty** [comment]
> test shared memory

You are very welcome @JanuszChmiel. Can you share how you test shared memory please? And also which programs do you use to listen to music from the 80s?

**Comment by JanuszChmiel** [comment]
The best shared memory benchmarking test is to run X11vnc without -noshm
So by running it
x11vnc -display :0 -bg -nopw -listen localhost -xkb -forever -ncache 10
-ncache_cr
Only if this app will not crash in this mode we will have 100 % insurance,
that shared memory on Android is implemented so perfectly like in original
Linux kernel. But I Am aware, that it will be a long way to reach this goal.
 
Next shared memory test is to run some apps which are intensively using
shared memory such as Pulseaudio sound server without option to disable
shared memory by using command line.
 
Sure, my favourite pcmanfm will still produce error caused by The fact, that
semaphores would had to be supported when using Termux and we must patiently
wait till this complex C programmers tasks willb e solved by Termux
specialists.
 
Shared memory is very important. There is also other app to test shared
memory with no need to use libandroidshmem.so library.
It is mysql
 
I have loved Gradio. It have worked perfectly for Me to listen my favourite
80 songs. But unfortunately,
radio-browser.info
WEB service have been redesigned and Gradio Vala source is helpless to work
with this new domain changes. And MR Haecker will never update Gradio again.
Because he has started with Shortwave, which will very probably never work
with ArchLinux or other Linux distro on Termux, because Libhandy C library
has issue to work and I do not know why, because even complex Mate desktop
work perfectly with Android from Termux and by using Proot.

**Comment by SDRausty** [comment]
@JanuszChmiel do you think it would be nice to have a script that would automate this?  Which of the methods you shared could be confined to using the command line without having to use x?

**Comment by JanuszChmiel** [comment]
Yes, it is even possible to use xinit and dummy video driver and X11vnc. BUt
it is technique is useful for sighted users only.
It is also possible to run only window manager and some GTK app. In this
case you will save memory.
Many mate apps can be executed with only Marco window manager and dbus.
dbus-run-session app aname &

**Comment by SDRausty** [comment]
> dummy video driver and X11vnc

Sounds like just the packages that we are looking for for this command line testing routine.  I hope they accomplish their task.

> sighted users only.

The result can be piped to any output we wish @JanuszChmiel; `espeak` and a play audio file command (so blind users can hear the spoken result of testing) come to mind.

**Comment by SDRausty** [comment]
> dummy video driver and X11vnc

Sounds like just the packages that we are looking for for this command line testing routine.  Thank you for sharing.  I hope they accomplish their task.

> sighted users only.

The result can be piped to any output we wish @JanuszChmiel; `espeak` and a play audio file command (so blind users can hear the spoken result of testing) come to mind.  What do you think of this proposed solution?

**Comment by SDRausty** [comment]
> fortunately to be found and usually quickly corrected, sometimes not, @xd003 are discussing an error which magically appeared the night before, then apparently disappeared by itself at this TermuxArch/TermuxArch#24 issue.

@JanuszChmiel thank you once more for sharing news about this error so quickly.  I was thinking about this anomaly and the one mentioned in issue 24 and its impact on the user base.   

To sum up, this error that you found @JanuszChmiel potentially impacted a lot of users, many users and could have remained undetected for quite some time. The reason being is that the effects of this error affects older model devices and/or older Android applications.  And as far as we know the unsupported post Android 5 user base is enormous.

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/termux-archlinux/commit/3e05493b8da82e9cde5971d56162be225dfa8eee resolves this issue at this git repository. I am really glad @JanuszChmiel that you managed to resolve the error in the meantime by following the instructions that were given 🎹 🎵
