### ISSUE TITLE
mkfifo with -m fails with error

### ISSUE THREAD

**Issue by rickysaurav** [SDRausty/termux-archlinux#70]
```mkfifo -m o+w /tmp/tmp_random ```
fails with the following error:
```mkfifo: cannot set permissions of '/tmp/tmp_random': Invalid argument```

This causes a lot of fzf commands to fail inside tmux with FZF_TMUX=1

**Comment by SDRausty** [comment]
@rickysaurav  I've noticed this too:
`[user17:55~]$ mkfifo -m o+w /tmp/tmp_random
mkfifo: cannot set permissions of '/tmp/tmp_random': Invalid argument`
It is created:
`[user17:56~]$ l /tmp/tmp_random
prw-r--r-- 1 user user 0 Oct 12 17:55 /tmp/tmp_random`
It has different permissions with the root user login:
`[root17:56~]$ l /tmp/tmp_random
prw-r--r-- 1 root root 0 Oct 12 17:55 /tmp/tmp_random`

The command `mkfifo -m o+w tmp_random` has no errors without proot; you might want to open an issue at https://github.com/termux/proot/issues to find out why there is an error with mkfifo in proot, but no error without proot.

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/termux-archlinux/commit/bd80df5dec9e0cf61f79639d0e125bce8cdfe57d makes the Termux command `makefifo`  easily accessible in Arch Linux Termux PRoot.   To access this Termux command in PRoot and a few more Termux command, you can refresh the installation with the `option` development placecard option: `setupTermuxArch option`.   The Termux command `makefifo` seems to fail the same way as the Arch Linux command in [PRoot with QEMU](https://github.com/TermuxArch/TermuxArch/issues/25).

**Comment by SDRausty** [comment]
@rickysaurav this issue, ["mkfifo -m error #126"](https://github.com/termux/proot/issues/126) is now open upstream.

**Comment by rickysaurav** [comment]
Cool, let's close this issue. I'll keep a track of it upstream.

**Comment by SDRausty** [comment]
`mkfifo -m o+w /tmp/tmp_random
mkfifo: cannot create fifo '/tmp/tmp_random': Function not implemented`

**Comment by SDRausty** [comment]
https://github.com/termux/proot/issues/141
