### ISSUE TITLE
git error:cannot store pack file

### ISSUE THREAD

**Issue by gauloics** [SDRausty/termux-archlinux#71]
![Screenshot_2020-10-19-01-45-12-66_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/742131/96377115-68c9c480-11ad-11eb-8574-5fb2b6cd4096.jpg)

why? 😭

**Comment by SDRausty** [comment]
```
[user15:56~]$ git clone https://github.com/SDRausty/TermuxArch
Cloning into 'TermuxArch'...
remote: Enumerating objects: 489, done.
remote: Counting objects: 100% (489/489), done.
remote: Compressing objects: 100% (264/264), done.
remote: Total 3201 (delta 240), reused 375 (delta 130), pack-reused 2712
Receiving objects: 100% (3201/3201), 13.62 MiB | 744.00 KiB/s, done.
Resolving deltas: 100% (1695/1695), done.
[user15:58~]$ d TermuxArch/
```
Cannot reproduce the error.  Try logging in as user.

**Comment by gauloics** [comment]
![Screenshot_2020-10-19-05-44-59-72_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/742131/96387706-4dbb7c80-11ce-11eb-9c69-6a37f9441789.jpg)

using the user account has no effect, this problem is not in the repository, maybe a storage problem.
I mean to put the git file into storage / shared / (a ​​folder).
it works fine using termux, but not arch
And, when using arch, git works fine in $ HOME, but not shared folders.

**Comment by SDRausty** [comment]
Thank you for clarifying where you are cloning.  The rules ARE a little bit different in shared storage.  Please try the [recently developed](https://github.com/SDRausty/termux-archlinux/issue_comments/689439499_) `elogin` option; `startarch el user`.  This should resolve the `cannot store pack file` error.

**Comment by SDRausty** [comment]
Thank you for clarifying where you are cloning @gauloics.  The rules ARE a little bit different in shared storage.  Please try the [recently developed](https://github.com/SDRausty/termux-archlinux/issues/51#issuecomment-689439499) `elogin` option; `startarch el user`.  This should resolve the `cannot store pack file` error.

**Comment by gauloics** [comment]
> Thank you for clarifying where you are cloning. The rules ARE a little bit different in shared storage. Please try the [recently developed](https://github.com/SDRausty/termux-archlinux/issue_comments/689439499_) `elogin` option; `startarch el user`. This should resolve the `cannot store pack file` error.

yeah, work well.
Thanks. 
Sorry for not opening github for a long time, I read your invitation via email , but didn't have time to open an account. ☺️🙏

**Comment by SDRausty** [comment]
You are welcome; And thank you for confirming:
```
yeah, work well.
```
