### ISSUE TITLE
Unable to run makefakeroottcp

### ISSUE THREAD

**Issue by xdrie** [SDRausty/termux-archlinux#72]
When I run `makefakeroottcp` as root I get a message that it should not be used as root.

When I run it as a standard user, it says "cannot create /data, operation not permitted"

**Comment by SDRausty** [comment]
Please see:
1. https://github.com/TermuxArch/TermuxArch/issues/22
1. https://github.com/TermuxArch/TermuxArch/issues/33
1. https://github.com/TermuxArch/TermuxArch/issues/37

**Comment by SDRausty** [comment]
Thank you regarding this information @xdrie 

> run `makefakeroottcp` as root

The TermuxArch command `makefakeroottcp` is not designed to be run as root; Hopefully this will be made clear to the root user by the 🕙 time the next version is released.

**Comment by xdrie** [comment]
Sorry, I am not able to run it as a regular user either because of the error I mentioned above

**Comment by SDRausty** [comment]
@xdrie this https://github.com/SDRausty/termux-archlinux/commit/16bc58e0ec936114c255799fbbee593a93f783b3 commit rewrites `makefakeroottcp` and this new version is ready for testing.  You can run `setupTermuxArch re` to update the installation and file `makefakeroottcp` to the newest version available.  When you have some time, please share your results here.

**Comment by xdrie** [comment]
It worked perfectly, thank you for the fix!

**Comment by SDRausty** [comment]
You are welcome @xdrie; thank you for helping.

**Comment by SDRausty** [comment]
The command `makefakeroottcp` has been fixed once more after being broken by upstream again.
