### ISSUE TITLE
Short wave Internet radio app building for AArch64

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#73]
I have decided that I will open this issue again. Shortwave can not be built successfully even when I have tried yay. Libhandy library is making issues.
If somebody would have A patience and if could assit Me when building Shortwave, please let Me know.

https://gitlab.gnome.org/World/Shortwave

Sure, I will work from AArch64 by using normally non emulated running Arch linux by using Termux and Proot.
Libhandy library is really very strange .so library.

**Comment by SDRausty** [comment]
Have you tried any of the libhandy precompiled packages?
```
$ startarch l user
[user13:58~]$ pcss Libhandy
extra/libhandy 1.0.2-1
    Library full of GTK+ widgets for mobile phones
extra/libhandy0 0.0.13+12+gaa6b6f4-2
    Library full of GTK+ widgets for mobile phones
[user13:58~]$ um
aarch64
```

**Comment by JanuszChmiel** [comment]
I have even built Shortwave successfully without crashes by using only git clone and some build commands. But resulting app have crashed. Because of some error message about cells so some internal app error related to Libhandy call. I will do it again to see, if there is no some progress. If no, I will have to kindly ask you, if you could find original author of Libhandy library. No some other users, who have cloned original and modified Libhandy repo. I must find Libhandy real primary developer if he would have a good will to find The cause of The issue.
Shortwave work for X86 or for X64 platforms.
But sure, using Qemu is not The way so I want to convince The original Libhandy author or authors to help.
Some users even uses flatpak, unfortunately it is only science fiction to use it on Chroot userspace Linux distribution, since Flatpak also love systém bus so it will never work without real Linux kernel and its kernel loops on background.
But running Shortwave by using Flatpak have some memory allocation disadvantages. It is something like isolated environment so it is ideal for security, but it allocates extra RAM. 
If my ateempt will fail, I will really be forced to simply use
Radio-browser.info
WEB site and its Javascript player which work like A charm.
But I love complex thinks to solve and I can learn something new thanks to so strange situations.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
@JanuszChmiel thank you for asking important questions.  These are some answers:

> original author of Libhandy library

```
yay libhandy
gcl https://aur.archlinux.org/libhandy-git.git
f url libhandy-git/PKGBUILD
```
Result:
`url="https://gitlab.gnome.org/GNOME/libhandy"`

> using Qemu 

Have you attrmpted to use the root user account to accomplish this goal with QEMU? The command `open4root` should be run before attempting to use this method. This new `open4root` command was designed because of user account emulation errors encountered with PRoot QEMU which do not happen without the `-q` option enabled.  

> Flatpak also love systém bus 

Is there any improvement after using the `csystemctl` command?  You might want to continue in a new session if command `csystemctl` wants to install the systemctl replacement.

**Comment by JanuszChmiel** [comment]
Dear MR Rausty,
Thank you very much for yours tip.
So if I will type csystemctl command it should solve errors related to problems with connecting to systém bus?
Or it is also necessary to add other options and commands to start some special services?
I will try csystemctl command again.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
> So if I will type csystemctl command it should solve errors related to problems with connecting to systém bus?

The `csystemctl` only automates intalling the `systemctl` replacement. It is not the `systemctl` command which does not appear to work correctly in PRoot, untill it is changed.
> Or it is also necessary to add other options and commands to start some special services?

TermuxArch uses this https://github.com/TermuxArch/docker-systemctl-replacement fork for the installation;  Feel free to ask questions about the `systemctl` replacement https://github.com/gdraheim/docker-systemctl-replacement/issues here.  That is where you can find the best answer to your question about using the `systemctl` commands.

**Comment by SDRausty** [comment]
> This new `open4root` command was designed

The `open4root` command is a wrapper for a simple `sed` command.  Hopefully, time will be found to add a user question along with user information to this newly implemented `open4root` command:
```
sed $(which open4root)
52:sed -i 's/UID\" = 0/UID\" = -1/g' /usr/local/bin/*
```
Please exercise caution after running it when using the PRoot root users login.  The login this command is designed for to assist in sofware development in Termux.

**Comment by SDRausty** [comment]
@JanuszChmiel I have two questions still waiting for answers to help resolve this topic;  One question asked in this issue, and another one asked in issue https://github.com/SDRausty/termux-archlinux/issues/62.
1. Have you tried installing any of the `libhandy` precompiled packages with `pci libhandy`?
2. Have you managed to build `gradio` successfully with `yay gradio`?

**Comment by JanuszChmiel** [comment]
Yes, I have compiled Gradio successfully with yay.
And precompiled Libhandy are causing issues when compiling. I have even tried to build Shortwave on standard Linux and it is really very tricky, since it did not worked for Me too.
Only some experts, who have prepared Flatpak precompiled build knows how to build it very probably.
Very strange app for building and to make build successfull.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by SDRausty** [comment]
@JanuszChmiel please see https://serviceanimals.github.io/Harper/ 

I just lost (bullets) mine; Do you have a guidedog? If not, why?

**Comment by SDRausty** [comment]
@JanuszChmiel have you heard the news regarding the death of our coder helper Harper? She was shot dead on 20201201 @1630. No water quality specialists are allowed to live in Flint, Michigan USA @present, only human set free water quality forgers!

Why was my water qualty specialist https://serviceanimals.github.io/Harper/ shot dead by Flint City Michigan USA police?

I asked the Flint City Mayor. They have not replied.

Do you have a guide dog?  Why not?

**Comment by JanuszChmiel** [comment]
It is very sad event. I Am very sad, that bad criminal individuals are killing people around. I AM very sorry, that I have got you engry thanks to my issues on Github. And that I have sent them in The bad day.
I wish you a nice day and I Am sharing sad feelings with you.
I hope, that harpers soul is in heaven and that angels will be around her.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz

**Comment by JanuszChmiel** [comment]
I Am giving you a big rest and you can close my all previously opened issues.
I have written this long comment about gnome-session as A demonstration, that I do not want to only overload all community members here, that I want to directly debate also with other developers to find A solution.
I have even debated with Fedora Linux programmers about dbus-session, which work very bad on Fedora in Proot. Sure, ArchLinux work very probably by The best way. 


Thank you for all The thinks, which you have done for Me and for future visually impaired people.
I wish you A nice chrystmass days. And be happy with yours family.


-- 
Tento e-mail byl zkontrolován na viry programem AVG.
http://www.avg.cz
