### ISSUE TITLE
Userspace mount

### ISSUE THREAD

**Issue by gordol** [SDRausty/termux-archlinux#74]
The discussion over here got locked...

https://github.com/termux/termux-app/issues/376

but

https://libguestfs.org/

it is possible...

Sorry if this isn't the best way to contact you.

Good luck!

**Comment by SDRausty** [comment]
Thank you for sharing that the `libguestfs` project exists @gordol; have you tried the command `yay libguestfs`?
```
[user11:42~]$ yay libguestfs
2 aur/libguestfs-git 1.42.0.r21.g4837698d8-1 (+0 0.00)
    Access and modify virtual machine disk image
1 aur/python-libguestfs 1.40.2-1 (+1 0.00)
    Python bindings for libguestfs
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==>
```
It appears that there are two versions of `libguestfs` via `yay`.  To create the `yay` command, you can use either `makeaurhelpers` or `makeyay` which attempt to build `yay` in Termux PRoot, with or without QEMU emulated architecture support.

**Comment by SDRausty** [comment]
> got locked

Because you found the solution we seek.   Integrating this code with PRoot like the QEMU option should probably solve the mount issue.

I have tried `yay guestfs` multiple times.  I am not getting a successful package build.  Are you having any luck building the Arch Linux guestfs packages?

**Comment by SDRausty** [comment]
citing _Originally posted by @xeffyr in https://github.com/termux/termux-app/issues/376#issuecomment-737185447_

> Look my answers above. No one here will bother to implement a tool for userspace image mounting. Please understand that possibilities of Termux maintainers are *finite*.

> Those who really needs mounting as non-root can use QEMU system-mode.

citing _Originally posted by @xeffyr in https://github.com/termux/termux-packages/issues/6141#issuecomment-743797540_

Start with these:
* x86 (32bit): https://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86/alpine-virt-3.12.2-x86.iso
* x86_64 (64bit): https://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86_64/alpine-virt-3.12.2-x86_64.iso

Boot downloaded image (basic):
```
qemu-system-i386 -m 512M -nographic -cdrom alpine-virt-3.12.2-x86.iso
```

Modified to boot from URL with no local image:
```
qemu-system-i386 -m 512M -nographic -boot d -drive file=https://dl-cdn.alpinelinux.org/alpine/v3.12/releases/x86/alpine-virt-3.12.2-x86.iso,readonly=on,media=cdrom
```
In both cases output is printed directly to console as image supports serial line emulated by QEMU.
`CTRL+a x` to terminate VM.

![qemu](https://user-images.githubusercontent.com/25881154/101991910-789aec00-3cb8-11eb-9e58-a789bd9bad8c.png)

Extending command line by switching to VirtIO devices (rng, nic, drives), increasing TCG cache (e.g. by `-accel tcg,tb-size=512`), using musl-based & non-systemd distributions like Alpine Linux makes execution under QEMU faster.

***

Arch Linux can be booted too, yet it is slower and ISO will require many RAM (1-2 GB, maybe more). Probably will have issues with text-only mode and you will need a VNC.

**Comment by SDRausty** [comment]
>it is possible...

@gordol it seems to be possible to build libguestfs with command [`makelibguestfs`](https://github.com/SDRausty/termux-archlinux/blob/master/archlinuxconfig.bash#L715&&#L913);  Can you please try command `makelibguestfs` and share your results?

**Comment by gordol** [comment]
silly bot. I'll try this soon, thanks @SDRausty
