### ISSUE TITLE
professional messages bus implementation needed

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#75]
Who of us knows, if there is some chance to make message bus implementation better than is today in Archlinux?
Is it possible to map some new virtual devices for /dev/fuse and other special devices folder so message bus will work really very near close to The state, when standard Linux kernel is presented?
I have debated with The author of csystemctl Python script. I Am aware, that we can not emulate system bus, because PCI bus is not presented on Android devices. And when we would try to do that, we would end on A stage that we would had to use Qemu and real Linux kernel with all of its sub processes. Which would mean extremely slow emulated distro, which would support all Linux features perfectly, but system would be so slow, that it would not be usable.
When I Am writing about Qemu.
Qemu accelerator  had two degrees.
User mode acceleration and full system mode acceleration. I knows that from one Windows app, Qemu manager. Which have used Kqemu accelerated Windows kernel driver. It not work with WIndows 10 kernel thought, only with WIndows XP kernel. Qemu manager have allowed to use partial user mode acceleration and full system acceleration.
So I Am dreaming, if it would not be possible to setup qemu user mode to accelerate on a user mode level, because we can not install Kqemu driver on AARCH64 and on other ARM CPUS.
If it is not possible, it is necessary to implement message bus as close as possible to real Linux distribution.
I know, that many apps run also now. But system message bus is not implemented as it should.
Because we can not emulate system bus, I have even tried to contact one of The gnome-session programmer. I have obtained his E-mail address from GNome-session source code. Sure, my true goal is to make Gnome desktop environment working atleast like mate-session can work.
We have shared memory support, but when I have looked inside gnome-session source C complex codes, I have found out, that it is too complex task to remove references to system bus communication for Me. COde refers to many C header files and I would end inside very complex code tree relationships.
So I have rather tried to ask one of The advanced GNome developers. I have kindly explained my goals, sure, he would be very probably not too glad thanks to my ideas.
I can not find out, why mate-session work so smoothly, and why gnome-session display error related to system bus connection and C code autoterminate immediately. Mate-session C source is programmed by The way, that this event do not cause auto termination.

**Comment by JanuszChmiel** [comment]
Even when using orcaconn script, which contain special systemctl command with some number as option, mate-session is still reporting
mate-session[16127]: WARNING: Could not connect to Systemd: Failed to connect to
 socket /run/dbus/system_bus_socket: AdresĂˇĹ™ nebo soubor neexistuje

**Comment by SDRausty** [comment]
@JanuszChmiel please see https://serviceanimals.github.io/Harper/ 

I just lost (bullets) mine; Do you have a guidedog? If not, why?

**Comment by SDRausty** [comment]
@JanuszChmiel have you heard the news regarding the death of our coder helper Harper? She was shot dead on 20201201 @1630. No water quality specialists are allowed to live in Flint, Michigan USA @present, only human set free water quality forgers!

Why was my water qualty specialist https://serviceanimals.github.io/Harper/ shot dead by Flint City Michigan USA police?

I asked the Flint City Mayor. They have not replied.

Do you have a guide dog?  Why not?

**Comment by SDRausty** [comment]
https://github.com/termux/proot/issues/141

**Comment by SDRausty** [comment]
The TermuxArch command `csystemctl` installs a `systemctl` replacement that seems to work as expected.
