### ISSUE TITLE
git doesn't seem to work on an external SD card

### ISSUE THREAD

**Issue by tunococ** [SDRausty/termux-archlinux#76]
git seems to be unable to create files on an external SD card. Somehow this is doable in the base Termux. What is the difference? Is it possible to make this work like in Termux or is this a limitation that cannot be overcome?

Here's a sequence of things I tried (all on the external SD card):
- Inside Arch, I called `git clone ...`, which failed with `error: unable to write file ...`.
- I called `git clone` in the base Termux and it succeeded.
- I modified a file and called `git add` inside Arch, and it failed with the same error message.
- I called `git add` in the base Termux and it succeeded.
- I called `git reset --hard` inside Arch and it succeeded.
- I modified the same file and called `git add` inside Arch. This time it succeeded.
- I called `git checkout -b newBranch` inside Arch and it succeeded.
- I called `git commit` inside Arch and it failed.
- I called `git commit` in the base Termux and it succeeded.

I can successfully create files on the external SD card inside Arch in several ways. (`cp`, `vim`, `cmake`, etc.) I have only encountered this problem with `git`.

I did several Google searches and they led me to speculate that this might have something to do with the file system on the external SD card, which I formatted as exFAT. However, the fact that `git` works fine in Termux is quite perplexing.

I tried setting `core.fileMode` to `false` and it didn't seem to help. (I didn't have to do that in the base Termux anyway.)

Please let me know how to fix this, if that's possible.

By the way, I'm using Lenovo Yoga SmartTab running Android 9 without root.

**Comment by tunococ** [comment]
I have also tried using Arch and Ubuntu via `proot-distro` and I ran into the same problem.

**Comment by SDRausty** [comment]
@tunococ thank you for sharing; are you familiar with these https://github.com/SDRausty/termuxarch/issues?q=is%3Aissue+git+external+is%3Aclosed topics?

**Comment by SDRausty** [comment]
> [el[ogin] user|eu[ser] user [options]] Login as user [plus options].  Use 'addauser user' first to create this user and the user's home directory.  This option is for working with programs that have already been installed, and for working with the 'git' command.

_Originally posted by @SDRausty in https://github.com/SDRausty/TermuxArch/issues/249#issuecomment-687776243_

Command `startarch h` has updated information.

**Comment by tunococ** [comment]
Ah. Thank you so much. My search skill wasn't good enough to find that. Following the instructions in `startarch h` for `elogin` solves the problem.

**Comment by SDRausty** [comment]
You are very welcome @tunococ;  Thanks for sharing.
