### ISSUE TITLE
AUR helper script

### ISSUE THREAD

**Issue by charlie39** [SDRausty/termux-archlinux#77]
Is there any helper script to install AUR packages ?

**Comment by SDRausty** [comment]
> Is there any helper script to install AUR

1 https://github.com/SDRausty/termux-archlinux/issues?q=is%3Aissue+AUR

2 https://github.com/TermuxArch/TermuxArch/issues?q=is%3Aissue+AUR

3 `makeaurhelpers` (partial implementation)
4 `makeyay`

PR https://github.com/TermuxArch/TermuxArch/pulls
