### ISSUE TITLE
Cant install anything 

### ISSUE THREAD

**Issue by MFDGaming** [sdrausty/termux-archlinux#8]
warning: Public keyring not found; have you run 'pacman-key --init'?
downloading required keys...
error: key "77193F152BDBE6A6" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (could not find or read file)
Errors occurred, no packages were upgraded.

**Comment by tsuchiura** [comment]
Just do 
$ keys
And everything related to pgp should be set.

**Comment by sdrausty** [comment]
`setupTermuxArch.sh refresh` might be helpful too.
