### ISSUE TITLE
Run arch on termux with normal user instead of root

### ISSUE THREAD

**Issue by elswerky** [SDRausty/termux-archlinux#85]
How to make arch in termux opens by default on any user other than root ??

I created new user but can't make arch boots with this user 

I want it to boot by default with user and 
Not to have use
 su username

Of you can help me

**Comment by SDRausty** [comment]
`bash setupTermuxArch h | grep default`

This link https://github.com/SDRausty/TermuxArch/issues/212 at GitHub has the most current information about setting Arch Linux in Termux PRoot as the default login shell in Termux in your smartphone, tablet, smartTV, wearable and more.  If you choose to, or are simply curious about setting Arch Linux in Termux PRoot as the default login shell, please be well acquainted with safe mode;  Long tapping on NEW SESSION will open a new session in safe mode.  This mode can be used to reset the default shell.

`startarch help`

startarch e[login|user] user  login as user.  Use alternate elogin and euser options to login as user.  This option is preferred for working with programs that have already been installed, and for working with the 'git' command.  Please use startarch c 'addauser user' first to create this user and the user's home directory.

startarch l[ogin]|u[ser] user  login as user.  This option is preferred when installing software from a user account with the 'sudo' command, and when using commands such as 'makeaurhelpers', 'makepkg' and 'makeyay'.  Please use 'addauser user' first to create this user and the user's home directory.

**Comment by elswerky** [comment]
startarch login username

**Comment by SDRausty** [comment]
You're welcome 🎵 🎶 ([eagles; hotel California](https://m.youtube.com/watch?v=FVsbvFkhzY4))
