### ISSUE TITLE
cp: missing destination file operand after '/data/data/com.termux/files/home/arc h'

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#88]
Setup script contain other little error.
cp: missing destination file operand after '/data/data/com.termux/files/home/arc
h'
refresh command do not help.
It is The price caused by The fact, that Archlinux is being developed so dynamically and you have to react on those very fast trends. So when you will have some time, please try to correct it.

Thank you. And I will try cache generation too, because I have enough storage space inside my phone.

**Comment by SDRausty** [comment]
Thank you for sharing!  I cannot reproduce this error at present; @JanuszChmiel  is this error still still present on your device?
