### ISSUE TITLE
Cannot login. user does not exist [Exit Signal 169]

### ISSUE THREAD

**Issue by gyurmogyuri** [SDRausty/termux-archlinux#89]
Dear SDRausty;
I used before. But after refresh I got error message.
[Exit Signal 169] my user is exist. Have in passwd and have home folder. Cannot login:
```
It appears that user 'gyurmo' does not exist in the Arch Linux in Termux PRoot system!  You can create user 'gyurmo' with the command startarch command 'addauser gyurmo' then rerun this comnand to login with user 'gyurmo';  Exiting...  startarch l gyurmo version 2.0.1547 [Exit Signal 169]: DONE  🏁 
```
i hope you will solve it.

**Comment by SDRausty** [comment]
>It appears that user 'gyurmo' does not exist in the Arch Linux in Termux PRoot system!  You can create user 'gyurmo' with the command startarch command 'addauser gyurmo' then rerun this comnand to login with user 'gyurmo';  Exiting...  startarch l gyurmo version 2.0.1547 [Exit Signal 169]: DONE  🏁 

> Exit Signal 169

Does directory `~/arch/home/gyurmo` exist?

**Comment by SDRausty** [comment]
Thank you for opening this issue @gyurmogyuri;  Can you please see whether refreshing with [the latest version](https://github.com/SDRausty/termux-archlinux/commit/5bb04c436cc8ff9205a2fce5811ee7c5f5634955) corrects the signal that you have very kindly shared.

**Comment by gyurmogyuri** [comment]
Good! After refresh is working fine. Thanks

**Comment by SDRausty** [comment]
You are welcome; And thank you!
