### ISSUE TITLE
severe Seamonkey internet suite crash occurred

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/termux-archlinux#92]
Dear elite C programmers, who are concentrated around this excellent series of Bash scripts. Some ArchLinux upgrade, may be an Termux package upgrade has caused sad fact. Seamonkey Internet suite do not work. It is impossible to execute Seamonkey at all. Firefox work. Seamonkey is my preferred ite because HTTML editor, IRC client and E-mail client is The part of this bundle.
How to reproduce The error?
Install ArchLinux by using latest up to date script from MR Rausty.
Instal The following packages.
pacman -S seamonkey orca mate mate-extra tigervnc
After installation, execute Tigervnc by using The following command
Xvnc :0 -SecurityTypes None &
Install BVNC app from Google Play store.
Connect to The VNC session by using Bvnc client.
run mate desktop environment by typing
dbus-run-session mate-session &
Zou can try to execute Seamonkey from The Internet application group from The panel.
Monitor The terminal console for AN error.

Seamonkey do not run.
Possible work arounds.
1. modify Proot start sequence inside startarch Bash script so build in shared memory support will not be used.
2. Try to execute Tigervnc with special option to disable shared memory extension
Xvnc :0 -SecurityTypes None -extension MIT-SHM&

Last possible and realistic solutions are.
1. replace VNC protocol by The Xserver Xsdl. I would had to plea sighted assistance to disable build in PUlseaudio in to Xserver Xsdl from The app settings dialog. Because Xserver Xsdl build in PUlseaudio is not compatible with Espeak-ng and it produces very unpleasant sound output. This not affect sighted majority.
2. I would had to replace Tigervnc by using Xorg and special dummy display driver and by using X11 vnc.

This approach is not very pleasant.
In all of those cases, it would be necessary to disable shared memory support build in to Proot from Startarch sequence.
I will try all those scenarios myselves. May be, that some elite developer would be so kind and could cooperate with Me to find The Seamonkey issue cause.

To avoid problems while working on The terminal I will be using mate-terminal and regular Fedora Linux distribution. Because only in those cases I Am sure, that I will be able to perfectly edit scripts in Nano with long delays and lack of some characters. It is not possible to reach this goal from Windows terminals and existing screen readers.
Unfortunately, Seamonkey is very complex bundle and I Am hrelpless to edit its source code and recompile it with some changes. To be honest, my programmers knowledge are too lov to reach this goal, because I would had to read many C source codes from used native .so libraryes.
It is not toy for The children so I will try to also debate on Arch Linux forums about The Seamonkey.

**Comment by yakovlevegor** [comment]
I confirm there is a segmentation fault when trying to run Seamonkey on vnc. Command line help messages show without crashing.

**Comment by yakovlevegor** [comment]
>     2. Try to execute Tigervnc with special option to disable shared memory extension
>        Xvnc :0 -SecurityTypes None -extension MIT-SHM&
This part doesn't appear to fix the issue for me, Seamonkey still crashes on Xvnc with `-extension MIT-SHM` option.

**Comment by yakovlevegor** [comment]
>     1. modify Proot start sequence inside startarch Bash script so build in shared memory support will not be used.
Removing all `/dev/shm` entries from `startarch` doesn't do the trick either.

**Comment by SDRausty** [comment]
These just published worldwide and beyond commands and similar ones might be useful in resolving this issue:
`makeaurhelpers f irc`
`makeaurhelpers f Seamonkey`
`makeaurhelpers f Tigervnc`
 `makeaurhelpers f Xvnc`

Command `makeaurhelpers help` has more information.

**Comment by SDRausty** [comment]
Has anyone attempted changing `unset LD_PRELOAD` to see whether this has an effect on vnc?

Has anyone attempted changing all memory references in `PROOTSTMNTU` to `$TMPDIR` on order to see whether this has an effect on vnc?

**Comment by SDRausty** [comment]
These just published worldwide and beyond commands and similar ones might be useful in resolving this issue:
`makeaurhelpers find irc`
`makeaurhelpers find monkey`
`makeaurhelpers view libxvnc`
 `makeaurhelpers view tigervnc-git`

Command `makeaurhelpers help` has the most recent information about usage for the recently redeployed `makeaurhelpers` command that was depreciated.
