### ISSUE TITLE
unable to install any package

### ISSUE THREAD

**Issue by vebhvv** [SDRausty/termux-archlinux#94]
Checked other app everything else working only except termux arch

![Screenshot_20220621-054954](https://user-images.githubusercontent.com/106908365/174692585-284ed28b-f053-4d06-a7fd-8f7f266fd91f.png)

**Comment by vebhvv** [comment]
@SDRausty  please sir look into this

**Comment by SDRausty** [comment]
Please update the pacman database;  The command `pci python` can be used to update the database and install python simultaneously.
