### ISSUE TITLE
pacman want to build kernel modules on Proot based environment

### ISSUE THREAD

**Issue by JanuszChmiel** [sdrausty/termux-archlinux#95]
Dear MR Rausty,
Pacman want to do its best to build Kernel modules on Proot environment. Please, is it possible to ban this behaviour?
I do not run Qemu variant of setuptermux arch script. Sure, I can press CTRL+c to break 56 times The process of building kernel modules and hooks, but it is not very pleasant.
Or is it impossible to disable this behaviour?

**Comment by SDRausty** [comment]
>build Kernel modules on Proot environment. Please, is it possible to ban this behaviour?

https://github.com/SDRausty/termux-archlinux/blob/master/archlinuxconfig.bash#L2031&&#L2086

>File /storage/emulated/0/Android/data/com.termux/files/cache/archlinux/arm64-v8a/DLTCCH not found.  If file /storage/emulated/0/Android/data/com.termux/files/cache/archlinux/arm64-v8a/DLTCCH is present with a 0, all the pkg cache files will be removed and trimming steps [1/6]-[6/6] will be used instead of steps [1/3]-[3/3].  Command 'cw trim)' has more information.  TermuxArch command 'trim' version 2.1.882: DONE
